//get project details
export const GET_USER_PROJECT_DETAILS_REQUEST = 'GET_USER_PROJECT_DETAILS_REQUEST';
export const GET_USER_PROJECT_DETAILS_REQUEST_SUCCESS = 'GET_USER_PROJECT_DETAILS_REQUEST_SUCCESS';
export const GET_USER_PROJECT_DETAILS_REQUEST_FAILED = 'GET_USER_PROJECT_DETAILS_REQUEST_FAILED';
export const GET_PROJECT_DETAILS_REQUEST = 'GET_PROJECT_DETAILS_REQUEST';
export const GET_PROJECT_DETAILS_REQUEST_SUCCESS = 'GET_PROJECT_DETAILS_REQUEST_SUCCESS';
export const GET_PROJECT_DETAILS_REQUEST_FAILED = 'GET_PROJECT_DETAILS_REQUEST_FAILED';

//get project reviews client wise
export const GET_PROJECT_REVIEWS_CLIENT_WISE = 'GET_PROJECT_REVIEWS_CLIENT_WISE';
export const GET_PROJECT_REVIEWS_CLIENT_WISE_SUCCESS = 'GET_PROJECT_REVIEWS_CLIENT_WISE_SUCCESS';
export const GET_PROJECT_REVIEWS_CLIENT_WISE_FAILED = 'GET_PROJECT_REVIEWS_CLIENT_WISE_FAILED';

//get project reviews client wise
export const GET_PROJECT_REVIEWS_FREELANCER_WISE = 'GET_PROJECT_REVIEWS_FREELANCER_WISE';
export const GET_PROJECT_REVIEWS_FREELANCER_WISE_SUCCESS = 'GET_PROJECT_REVIEWS_FREELANCER_WISE_SUCCESS';
export const GET_PROJECT_REVIEWS_FREELANCER_WISE_FAILED = 'GET_PROJECT_REVIEWS_FREELANCER_WISE_FAILED';

//get project contract detail
export const GET_USER_PROJECT_CONTRACT_DETAILS_REQUEST = 'GET_USER_PROJECT_CONTRACT_DETAILS_REQUEST';
export const GET_USER_PROJECT_CONTRACT_DETAILS_REQUEST_SUCCESS = 'GET_USER_PROJECT_CONTRACT_DETAILS_REQUEST_SUCCESS';
export const GET_USER_PROJECT_CONTRACT_DETAILS_REQUEST_FAILED = 'GET_USER_PROJECT_CONTRACT_DETAILS_REQUEST_FAILED';

//get client  detail
export const GET_CLIENT_DETAIL_BY_USER_ID_REQUEST = 'GET_CLIENT_DETAIL_BY_USER_ID_REQUEST';
export const GET_CLIENT_DETAIL_BY_USER_ID_REQUEST_SUCCESS = 'GET_CLIENT_DETAIL_BY_USER_ID_REQUEST_SUCCESS';
export const GET_CLIENT_DETAIL_BY_USER_ID_REQUEST_FAILED = 'GET_CLIENT_DETAIL_BY_USER_ID_REQUEST_FAILED';
export const GET_CLIENT_DETAIL_BY_USER_ID_REQUEST_CLEANUP = 'GET_CLIENT_DETAIL_BY_USER_ID_REQUEST_CLEANUP';

//project post
export const PROJECT_POST_GET_PROJECT_DETAILS = 'PROJECT_POST_GET_PROJECT_DETAILS';

//project post - post
export const PROJECT_POST_UPDATE_PROJECT_TYPE = 'PROJECT_POST_UPDATE_PROJECT_TYPE';
export const PROJECT_POST_UPDATE_PROJECT_SCOPE = 'PROJECT_POST_UPDATE_PROJECT_SCOPE';
export const PROJECT_POST_UPDATE_SELECTED_SERVICES='PROJECT_POST_UPDATE_SELECTED_SERVICES'
export const PROJECT_POST_UPDATE_PROJECT_SUB_SCOPE = 'PROJECT_POST_UPDATE_PROJECT_SUB_SCOPE';

export const PROJECT_POST_UPDATE_FIELD = 'PROJECT_POST_UPDATE_FIELD';

//post project - project details
export const PROJECT_POST_JOB_TITLE_CHANGED = 'PROJECT_POST_JOB_TITLE_CHANGED';
export const PROJECT_POST_JOB_DESCRIPTION_CHANGED = 'PROJECT_POST_JOB_DESCRIPTION_CHANGED';
export const PROJECT_POST_ADD_DOCUMENT = 'PROJECT_POST_ADD_DOCUMENT';
export const PROJECT_POST_REMOVE_DOCUMENT = 'PROJECT_POST_REMOVE_DOCUMENT';

//post project - milestone/hourly
export const PROJECT_POST_ADD_SKILL = 'PROJECT_POST_ADD_SKILL';
export const PROJECT_POST_REMOVE_SKILL = 'PROJECT_POST_REMOVE_SKILL';
export const PROJECT_POST_UPDATE_FREELANCER_TYPE = 'PROJECT_POST_UPDATE_FREELANCER_TYPE';
export const PROJECT_POST_UPDATE_FREELANCER_COUNT = 'PROJECT_POST_UPDATE_FREELANCER_COUNT';
export const PROJECT_POST_UPDATE_PERIOD = 'PROJECT_POST_UPDATE_PERIOD';
export const PROJECT_POST_UPDATE_CURRENCY = 'PROJECT_POST_UPDATE_CURRENCY';
export const PROJECT_POST_UPDATE_AMOUNT = 'PROJECT_POST_UPDATE_AMOUNT';
export const PROJECT_POST_UPDATE_MAX_WEEK_HOURS = 'PROJECT_POST_UPDATE_MAX_WEEK_HOURS';

//post project - free contract
export const PROJECT_POST_UPDATE_NO_OF_DAY = 'PROJECT_POST_UPDATE_NO_OF_DAY';
export const PROJECT_POST_UPDATE_AMOUNT_PER_DAY = 'PROJECT_POST_UPDATE_AMOUNT_PER_DAY';

//post project - post office
export const PROJECT_POST_UPDATE_SALARY_TYPE = 'PROJECT_POST_UPDATE_SALARY_TYPE';
export const PROJECT_POST_UPDATE_FROM_SALARY = 'PROJECT_POST_UPDATE_FROM_SALARY';
export const PROJECT_POST_UPDATE_TO_SALARY = 'PROJECT_POST_UPDATE_TO_SALARY';
export const PROJECT_POST_UPDATE_POSITION_AVAILABLE_DATE = 'PROJECT_POST_UPDATE_POSITION_AVAILABLE_DATE';

export const PROJECT_POST_UPDATE_LIFECYCLE_STAGE = 'PROJECT_POST_UPDATE_LIFECYCLE_STAGE';
export const PROJECT_POST_UPDATE_MINIMUM_REQUIREMENT_FIELD = 'PROJECT_POST_UPDATE_MINIMUM_REQUIREMENT_FIELD';
export const PROJECT_POST_UPDATE_SCREENING_QUESTIONS = 'PROJECT_POST_UPDATE_SCREENING_QUESTIONS';
export const PROJECT_POST_UPDATE_IS_COVER_LETTER_REQUIRED = 'PROJECT_POST_UPDATE_IS_COVER_LETTER_REQUIRED';
export const PROJECT_POST_UPDATE_PROBATION_PERIOD = 'PROJECT_POST_UPDATE_PROBATION_PERIOD';
export const PROJECT_POST_UPDATE_PER_HOUR_AMOUNT='PROJECT_POST_UPDATE_PER_HOUR_AMOUNT'
export const PROJECT_POST_UPDATE_OFFERED_MILESTONE="PROJECT_POST_UPDATE_OFFERED_MILESTONE"
export const PROJECT_POST_SUCCESSFULLY_DONE="PROJECT_POST_SUCCESSFULLY_DONE"
export const PROJECT_POST_UPDATE_AMOUNT_FREE_CONTRACT="PROJECT_POST_UPDATE_AMOUNT_FREE_CONTRACT"
export const CLIENT_REGISTRATION_SINGLE_PARAM="CLIENT_REGISTRATION_SINGLE_PARAM"
export const FREELANCER_REGISTRATION_PROFILE="FREELANCER_REGISTRATION_PROFILE"
export const CLIENT_REGISTRATION_SINGLE_PARAM_OPTIONAL="CLIENT_REGISTRATION_SINGLE_PARAM_OPTIONAL"
export const ORGANIZATION_REGISTRATION_PROFILE="ORGANIZATION_REGISTRATION_PROFILE"