import { PROD_API } from "./common";

//KEY NAME MUST UNIQUE AND DO NOT CHANGE WIHTOUT ASKING !!
// Write in ABC order
export const ENDPOINT = {
  //comment for create new user
  CreateNewUser: `${PROD_API.LOGIN_MICROSERVICE}/api/account/CreateNewUser`,
  CreateNewUserBySNS: `${PROD_API.LOGIN_MICROSERVICE}/api/account/CreateNewUserBySNS`,
  CreateInquiry: `${PROD_API.LOGIN_MICROSERVICE}/api/Inquiry/CreateInquiry`,
  GetRegionByCountry: `${PROD_API.UTILITY_MICROSERVICE}/api/Region/GetRegionByCountry`,
  GetSettingInfo: `${PROD_API.SETTING_MICROSERVICE}/api/settings/GetSettings`,
  GetChannelInfo: `${PROD_API.CHANNEL_MICROSERVICE}/api/channel/GetChannelInfo`,
  GetCrossDomain: `${PROD_API.LOGIN_MICROSERVICE}/api/CrossDomain/GetCrossDomain`,
  GetPointCardInfo: `${PROD_API.POINTCARD_MICROSERVICE}/api/PointCard/GetPointCardInfo`,
  LoginJungleTalk: `${PROD_API.LOGIN_MICROSERVICE}/api/account/LoginJungleTalk`,
  NotificationCreation: `${PROD_API.USER_ADDRESS}/api/ThirdPartyApp/NotificationCreation`,
  ResetJungleTalkPassword: `${PROD_API.LOGIN_MICROSERVICE}/api/account/ResetJungleTalkPassword`,
  SetSettingTab: `${PROD_API.SETTING_MICROSERVICE}/api/settings/SaveSettings`,
  SocialLogin: `${PROD_API.LOGIN_MICROSERVICE}/api/SNSLogin/SocialLogin`,
  VerifyEmail: `${PROD_API.LOGIN_MICROSERVICE}/api/account/VerifyEmail`,


  // User token getting microservices
  GetToken: `${PROD_API.AUTH_TOKEN_IMAGES_MICROSERVICE}/api/Auth/GetToken`,

  // invitation api's
  InterviewInvitation: `${PROD_API.PROJECT_MICROSERVICE}/api/Invitation/InterviewInvitation`,
  GetPropposalInvitationsByFreelancer: `${PROD_API.PROJECT_MICROSERVICE}/api/Invitation/GetPropposalInvitationsByFreelancer`,
  UpdateInviewStatus: `${PROD_API.PROJECT_MICROSERVICE}/api/Invitation/UpdateInviewStatus`,

  GetAllProjects: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetAllProjects`,
  GetFreelancerOnGoingProjects: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetFreelancerOnGoingProjects`,
  GetFreelancerProjectSummary: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetFreelancerProjectSummary`,
  GetClientProjectSummary: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetClientProjectSummary`,
  GetProjectsRecruitment: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetProjectsRecruitment`,
  GetFeaturedContests: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetFeaturedContests`,
  GetFreelancersContest: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetFreelancersContest`,
  GetClientsContest: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetClientsContest`,
  SearchProjects: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/SearchProjects`,
  GetFreelancerProjects: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetFreelancerProjects`,
  GetClientProjects: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetClientProjects`,
  GetProject: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetProject`,
  GetProjectContest: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetProjectContest`,
  GetShortListedProjects: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetShortListedProjects`,
  GetProjectDetail: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetProjectDetail`,
  GeneralSettings: `${PROD_API.PROJECT_MICROSERVICE}/api/GeneralSetting/GetGeneralSettings`,
  UpdateGeneralSetting: `${PROD_API.PROJECT_MICROSERVICE}/api/GeneralSetting/UpdateGeneralSetting`,
  AddGeneralSetting: `${PROD_API.PROJECT_MICROSERVICE}/api/GeneralSetting/AddGeneralSettings`,
  DeleteGeneralSetting: `${PROD_API.PROJECT_MICROSERVICE}/api/GeneralSetting/DeleteGeneralSettings`,

  GetUserExistingProjects: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetUserExistingProjects`,
  GetProjectDetails: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetProjectDetails`,
  CreateProject: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/CreateProject`,
  UpdateProjectInitStep: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateProjectInitStep`,
  GetProjectBidding: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetProjectBidding`,
  GetProjectProposalsByFilteredFreelancer: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/GetProjectProposalsByFilteredFreelancer`,
  UpdateProjectStep2: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateProjectStep2`,
  UpdateProjectSecondStep: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateProjectSecondStep`,
  UpdateFreeContractProfessions: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateFreeContractProfessions`,
  UpdateMilestoneProjectStep3: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateMilestoneProjectStep3`,
  UpdateFreeContractProjectStep3: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateFreeContractProjectStep3`,
  UpdateOfficeWorkProjectStep3: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateOfficeWorkProjectStep3`,
  UpdateHourlyProjectStep3: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateHourlyProjectStep3`,
  UpdateProjectThirdStep: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateProjectThirdStep`,
  UpdateContestProjectStep3: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateContestProjectStep3`,
  UpdateContestProject: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateContestProject`,
  UpdateProjectPost: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateProjectPost`,
  CreateContest: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/CreateContest`,
  CreateContestProject: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/CreateContestProject`,
  CreateProposal: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/CreateProposal`,
  GetFirstPassParticipants: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/GetFirstPassParticipants`,
  GetContestWinners: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/GetContestWinners`,
  SelectFirstPassParticipants: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/SelectFirstPassParticipants`,
  SelectContestWinners: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/SelectContestWinners`,
  CreateContestProposal: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/CreateContestProposal`,
  AvailableToPropose: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/AvailableToPropose`,
  UpdateProposal: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/UpdateProposal`,
  GetProposal: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/GetProposal`,
  WithdrawProposal: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/WithdrawProposal`,
  GetUserProposals: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/GetUserProposals`,
  GetProjectProposals: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/GetProjectProposals`,
  HiredProposal: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectProposal/HiredProposal`,
  GetUserOffers: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/GetUserOffers`,
  GetProjectContractHistory: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/GetProjectContractHistory`,
  HoldContract: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/HoldContract`,
  ResumeContract: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/ResumeContract`,
  EndContract: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/EndContract`,
  GetContractsByClient: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/GetContractsByClient`,
  UpdateContractCondition: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/UpdateContractCondition`,
  GetOfferContracts: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/GetOfferContracts`,
  CreateProjectContract: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/CreateProjectContract`,
  GetClientOffers: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/GetClientOffers`,
  GetUserOffer: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/GetUserOffer`,
  OfferDecline: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/OfferDecline`,
  DeclineContractOffer: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/DeclineContractOffer`,
  OfferAccept: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/OfferAccept`,
  AcceptContractOffer: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/AcceptContractOffer`,
  GetContractsByFreelancer: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/GetContractsByFreelancer`,
  CreatePackageRequest: `${PROD_API.PROJECT_MICROSERVICE}/api/PackageRequest/CreatePackageRequest`,
  UpdatePackageRequest: `${PROD_API.PROJECT_MICROSERVICE}/api/PackageRequest/UpdatePackageRequest`,
  UpdatePackageRequestAssignUser: `${PROD_API.PROJECT_MICROSERVICE}/api/PackageRequest/UpdatePackageRequestAssignUser`,
  UpdatePackageRequestDocument: `${PROD_API.PROJECT_MICROSERVICE}/api/PackageRequest/UpdatePackageRequestDocument`,
  GetPackageRequests: `${PROD_API.PROJECT_MICROSERVICE}/api/PackageRequest/GetPackageRequests`,
  GetPackageRequest: `${PROD_API.PROJECT_MICROSERVICE}/api/PackageRequest/GetPackageRequest`,
  UpdateHireMoreFreelancer: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/UpdateHireMoreFreelancer`,

  // Individual Freelancer
  CreateFreelancerUser: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/CreateFreelancer`,
  UpdateFreelancer: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/UpdateFreelancer`,
  Confirm: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/Confirm`,
  GetAllFreelancers: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetAllFreelancers`,
  UpdateFreelancerBasicInfo: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/UpdateFreelancerBasicInfo`,
  UpdateFreelancerServices: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/UpdateFreelancerServices`,
  UpdateFreelancerResume: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/UpdateFreelancerResume`,
  GetIndividualFreelancer: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetIndividualFreelancer`,
  GetIndividualFreelancerByUserId: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetIndividualFreelancerByUserId`,
  UpdateFreelancerAccount: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/UpdateFreelancerAccount`,
  UpdateFreelancerImages: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/UpdateFreelancerImages`,
  GetNerbyProjects: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetNerbyProjects`,
  GetRecommendedFreelancers: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetRecommendedFreelancers`,
  GetPortfoliosFreelancer: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetPortfolios`,
  GetSkillsFreelancer: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetSkills`,
  AddShortListedProject: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/AddShortListedProject`,
  RemoveShortListedProject: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/RemoveShortListedProject`,
  
  // OrganizationFreelancer
  InviteFreelancerToJoinCompany: `${PROD_API.USER_MICROSERVICE}/api/OrganizationFreelancer/InviteFreelancerToJoinCompany`,
  GetInvitedFreelancersByOrganization: `${PROD_API.USER_MICROSERVICE}/api/OrganizationFreelancer/GetInvitedFreelancersByOrganization`,
  UpdateInvitationStatus: `${PROD_API.USER_MICROSERVICE}/api/OrganizationFreelancer/UpdateInvitationStatus`,
  GetOrganizationInvitesByFreelancer: `${PROD_API.USER_MICROSERVICE}/api/OrganizationFreelancer/GetOrganizationInvitesByFreelancer`,
  GetFreelancersByOrganization: `${PROD_API.USER_MICROSERVICE}/api/OrganizationFreelancer/GetFreelancersByOrganization`,
  GetOrganizationStatsByOrganizationId: `${PROD_API.USER_MICROSERVICE}/api/OrganizationFreelancer/GetOrganizationStatsByOrganizationId`,
  DeleteOrganizationFreelancerInvite: `${PROD_API.USER_MICROSERVICE}/api/OrganizationFreelancer/DeleteOrganizationFreelancerInvite`,
  AddOrganizationFreelancerToTeam: `${PROD_API.USER_MICROSERVICE}/api/OrganizationFreelancer/AddOrganizationFreelancerToTeam`,
  UpdateFullTimeAvailability: `${PROD_API.USER_MICROSERVICE}/api/OrganizationFreelancer/UpdateFullTimeAvailability`,
  // team organization
  CreateOrganizationTeam: `${PROD_API.USER_MICROSERVICE}/api/OrganizationTeam/CreateOrganizationTeam`,
  GetAllOrganizationTeams: `${PROD_API.USER_MICROSERVICE}/api/OrganizationTeam/GetAllOrganizationTeams`,
  ActivateOrDeactivateTeam: `${PROD_API.USER_MICROSERVICE}/api/OrganizationTeam/ActivateOrDeactivateTeam`,

  // Reports
  AddNewFreelancerFeedback: `${PROD_API.REPORTS_MICROSERVICE}/api/FreelancerFeedback/AddNewFreelancerFeedback`,
  AddNewClientFeedback: `${PROD_API.REPORTS_MICROSERVICE}/api/ClientFeedback/AddNewClientFeedback`,
  AddNewOrganizationFeedback: `${PROD_API.REPORTS_MICROSERVICE}/api/OrganizationFeedback/AddNewOrganizationFeedback`,
  // Company freelancer
  CreateOrganization: `${PROD_API.USER_MICROSERVICE}/api/Organization/CreateOrganization`,
  UpdateOrganization: `${PROD_API.USER_MICROSERVICE}/api/Organization/UpdateOrganization`,
  UpdateOrganizationAccount: `${PROD_API.USER_MICROSERVICE}/api/Organization/UpdateOrganizationAccount`,
  UpdateOrganizationImages: `${PROD_API.USER_MICROSERVICE}/api/Organization/UpdateOrganizationImages`,
  UpdateOrganizationServices: `${PROD_API.USER_MICROSERVICE}/api/Organization/UpdateOrganizationServices`,
  GetOrganization: `${PROD_API.USER_MICROSERVICE}/api/Organization/GetOrganization`,
  UpdateOrganizationBasicInfo: `${PROD_API.USER_MICROSERVICE}/api/Organization/UpdateOrganizationBasicInfo`,
  UpdateInvitation: `${PROD_API.USER_MICROSERVICE}/api/Organization/UpdateInvitation`,
  UpdateOrganizationDetail: `${PROD_API.USER_MICROSERVICE}/api/Organization/UpdateOrganizationDetail`,
  UpdateOrganizationPortfolio: `${PROD_API.USER_MICROSERVICE}/api/Organization/UpdateOrganizationPortfolio`,
  GetPortfoliosOrganization: `${PROD_API.USER_MICROSERVICE}/api/Organization/GetPortfolios`,
  GetSkillsOrganization: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetSkills`,

  // User Client
  GetMyFreelancers: `${PROD_API.USER_MICROSERVICE}/api/Client/GetMyFreelancers`,
  CreateUserClient: `${PROD_API.USER_MICROSERVICE}/api/Client/CreateUserClient`,
  GetUserClient: `${PROD_API.USER_MICROSERVICE}/api/Client/GetUserClient`,
  UpdateUserClient: `${PROD_API.USER_MICROSERVICE}/api/Client/UpdateUserClient`,
  UpdateClientProfileImage: `${PROD_API.USER_MICROSERVICE}/api/Client/UpdateClientProfileImage`,
  UpdatePortfolios: `${PROD_API.USER_MICROSERVICE}/api/Client/UpdatePortfolios`,
  UploadOfficePhotos: `${PROD_API.USER_MICROSERVICE}/api/Client/UploadOfficePhotos`,
  GetNearbyFreelancers: `${PROD_API.USER_MICROSERVICE}/api/Client/GetNearbyFreelancers`,
  // user headhunter
  CreateHeadhunter: `${PROD_API.USER_MICROSERVICE}/api/HeadHunter/CreateHeadhunter`,

  // GetClientDetails: `${PROD_API.USER_MICROSERVICE}/api/Client/GetUserClient`,

  // CreateOrganization: `${PROD_API.USER_MICROSERVICE}/api/User/CreateOrganization`,
  // GetOrganization: `${PROD_API.USER_MICROSERVICE}/api/User/GetOrganization`,
  UpdateOrganizationProfile: `${PROD_API.USER_MICROSERVICE}/api/User/UpdateOrganizationProfile`,
  DeleteOrganization: `${PROD_API.USER_MICROSERVICE}/api/User/DeleteOrganization`,
  CreateUser: `${PROD_API.USER_MICROSERVICE}/api/User/CreateUser`,
  GetUser: `${PROD_API.USER_MICROSERVICE}/api/User/GetUser`,
  GetAccount: `${PROD_API.USER_MICROSERVICE}/api/User/GetAccount`,
  GetRegisteredUserTypes: `${PROD_API.USER_MICROSERVICE}/api/User/GetRegisteredUserTypes`,
  UpdateUserProfile: `${PROD_API.USER_MICROSERVICE}/api/User/UpdateUserProfile`,
  AddProjectReview: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectReview/AddProjectReview`,
  CompleteProjectContract: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/CompleteProjectContract`,

  // GetAllFreelancers: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetAllFreelancers`,
  // GetMyFreelancers: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetMyFreelancers`,
  GetMyFreelancersList: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetMyFreelancersList`,
  GetClientDetails: `${PROD_API.USER_MICROSERVICE}/api/Freelancer/GetClientDetail`,
  GetUserTimeTracking: `${PROD_API.USER_MICROSERVICE}/api/UserTimeTracking/GetUserTimeTracking`,
  GetProjectUserTimeTracking: `${PROD_API.USER_MICROSERVICE}/api/UserTimeTracking/GetProjectUserTimeTracking`,
  GetTimeSummary: `${PROD_API.TIME_TRACKER_MICROSERVICE}/api/TimeTracking/GetTimeSummary`,
  GetFreelancerActivityDetails: `${PROD_API.TIME_TRACKER_MICROSERVICE}/api/TimeTracking/GetFreelancerActivityDetails`,
  GetFreelancerTimeSessionDetails: `${PROD_API.TIME_TRACKER_MICROSERVICE}/api/TimeSession/GetFreelancerTimeSessionDetails`,
  GetWeeklySummary: `${PROD_API.TIME_TRACKER_MICROSERVICE}/api/TimeTracking/GetWeeklySummary`,
  AddManualTime: `${PROD_API.TIME_TRACKER_MICROSERVICE}/api/TimeSession/AddManualTime`,
  DeactivatedUser: `${PROD_API.USER_MICROSERVICE}/api/User/DeactivatedUser`,
  UpdateUserResumeDetail: `${PROD_API.USER_MICROSERVICE}/api/User/UpdateUserResumeDetail`,
  GetAllUsers: `${PROD_API.USER_MICROSERVICE}/api/User/GetAllUsers`,

  // images upload service
  UpdateImage: `${PROD_API.IMAGES_MICROSERVICE}/api/Utility/UpdateImage`,
  UploadImage: `${PROD_API.IMAGES_MICROSERVICE}/api/Utility/UploadImage`,
  DeleteImage: `${PROD_API.IMAGES_MICROSERVICE}/api/Utility/DeleteImage`,
  UpdateVideo: `${PROD_API.IMAGES_MICROSERVICE}/api/Utility/UpdateVideo`,
  UploadFiles: `${PROD_API.IMAGES_MICROSERVICE}/api/Utility/UploadFiles`,
  S3KeyToURL: `${PROD_API.IMAGES_MICROSERVICE}/api/Utility/S3KeyToURL`,
  GetServiceCategories: `${PROD_API.IMAGES_MICROSERVICE}/api/Utility/GetServiceCategories`,
  GetServicesByCategory: `${PROD_API.IMAGES_MICROSERVICE}/api/Utility/GetServicesByCategory`,

  CreateProjectDispute: `${PROD_API.DISPUTE_MICROSERVICE}/api/ProjectDispute/CreateProjectDispute`,
  CreateProjectDisputeCounterOffer: `${PROD_API.DISPUTE_MICROSERVICE}/api/ProjectDispute/CreateProjectDisputeCounterOffer`,
  ApproveProjectDispute: `${PROD_API.DISPUTE_MICROSERVICE}/api/ProjectDispute/ApproveProjectDispute`,
  RejectProjectDispute: `${PROD_API.DISPUTE_MICROSERVICE}/api/ProjectDispute/RejectProjectDispute`,
  GetFreelancerProjectDisputes: `${PROD_API.DISPUTE_MICROSERVICE}/api/ProjectDispute/GetFreelancerProjectDisputes`,
  GetClientProjectDisputes: `${PROD_API.DISPUTE_MICROSERVICE}/api/ProjectDispute/GetClientProjectDisputes`,
  GetProjectDetails1: `${PROD_API.PROJECT_MICROSERVICE}/api/Project/GetProjectDetails`,
  GetProjectReviewClientWise: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectReview/GetProjectReviewClientWise`,
  GetProjectReviewFreeLancerWise: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectReview/GetProjectReviewFreeLancerWise`,
  GetProjectContractDetail: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/GetProjectContractDetail`,
  AddProjectHistory: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectHistory/AddProjectHistory`,
  GetProjectHistories: `${PROD_API.PROJECT_MICROSERVICE}/api/ProjectHistory/GetProjectHistories`,
  PostUserAddress: `${PROD_API.USER_ADDRESS}/api/User/AddUserAddress`,
  GetUserAddress: `${PROD_API.USER_ADDRESS}/api/User/GetUserAddress`,
  UpdateUserAddress: `${PROD_API.USER_ADDRESS}/api/User/ModifyUserAddress`,
  DeleteUserAddress: `${PROD_API.USER_ADDRESS}/api/User/DeleteUserAddress`,
  UpdateProjectContract: `${PROD_API.CONTRACT_MICROSERVICE}/api/ProjectContract/UpdateProjectContract`,
  GetKeyValue: `${PROD_API.UTILITY_MICROSERVICE_NEW}/api/KeyManager/GetKeys`,

  //dispute 
  AddDisputeRefund: `${PROD_API.DISPUTE_MICROSERVICE}/api/Dispute/AddDisputeRefund`,
};
