export const MainTextEnglish = {
  ABOUT_YOUR_PAYMENT: "About Your Payment",
  ACCOUNTING_TEXT: "Legal/Accounting",
  ACTION: "Action",
  ACTION_TEXT: "Action",
  ACTIVE_SINCE_TEXT: "Active since",
  ADD_MORE_SERVICES: "Add More Services",
  ADD_REQUIRED_SKILLS: "Add Required Skills",
  ADD_FREELANCER: "Add Freelancer",
  ADDRESS_TEXT: "Address",
  ADDRESS_TEXT_BUTTON: "Register Address",
  ADD_SCREENING_QUESTION:
    "Add screening questions so freelancers can answer when submitting the proposal.",
  ADDITIONAL_PROJECT_FILES: "Additional project files (optional)",
  ADD_PHOTO: "Add a Photo",
  ADMIN: "Admin",
  ADD_SECOND_THIRD_PRIZE_DES:
  " Additional award increases chances for the designers to win and therefore attracts more designers",
  ALL_FREELANCERS: "All Freelancers",
  ALL_MY_POSTS: "All My Posts",
  ALL_PROJECTS: "All Projects",
  ALL_PACKAGES: "All Packages",
  ALL_PROJECTS_SUB: "Find projects, that most suitable for you",
  ALLOW_CHANGE_PARTICIPANTS: "Allow to change participants",
  ALLOW_FREELANCER_LOG_TIME_MANU: "Allow freelancer to log time manually if needed",
  AMOUNT_OF_WINNING: "The amount of winning award",
  APP_DEVELOPMENT: "App/Software",
  APPLICANTS_TEXT: "Applicants",
  ATTACH_ADDITIONAL_DESIGN:
    "Attach your image file that you want the similar style of design",
  AWARDS_TEXT: "Awards",
  ADD_SECOND_THIRD_PRIZE: "  Add 2nd, 3rd places prize",
  ADDRESS: "Address",
  AREA_TO_STUDY: "Area to study/Department",
  AVAILABLE_PER_WEEK: "Availability Per Week",
  AVAILABLE_PER_WEEK_REQUIRED: "Availability Per Week is Required!",
  AVAILABILITY_TEXT: "Availability",
  APPLY_PROBATION_PERIOD: "Apply Probation Period",
  AND_TEXT: "and",
  ADMIN_PASSWORD: "Admin password",
  ANNUAL_SALES: "Annual Sales",
  LINKEDIN_PROFILE_URL:"Linkedin profile Url",
  ABSTRACT: "Abstract",
  ATTENDANCE: "Attendance",
  AWARD_GURANTEED: "Award Guaranteed",
  AWARD_CERTIFICATE: "Award Certificate",
  AWARD_CERTIFICATE_BUTTON: "Add your award certificate",
  ACCEPT_INTERVIEW: "Accept Interview",
  // END OF A

  BACK: "Back",
  BALANCE_DUE: "Balance Due",
  BANNER_MAIN_FIRST: "The Most Effective Way of",
  BANNER_MAIN_SECOND: "Managing Your Work.",
  BANNER_MAIN_THIRD:
    "베어롤에서는 프로젝트는 물론 시간별 고용이 가능하여  고용인에게는 업무효율의 극대화를 프리랜서에게는 시간의 가치를 제공합니다.",
  BANNER_MAIN_FORTH:
    "정글토크에서 제공하는 프로젝트 관리 프로그램을 활용하여 실시간 채팅 및 파일 업무관리 관리 다양한 관리툴을 무료로 사용하실수 있습니다.",
  BLIND_TEXT: "Blind",
  BLIND_DETAIL:
    " Increase Creativity - block designers from seeing each other entries",
  BUDGET_TEXT: "Budget",
  BUSINESS_SCOPE: "Business Scope",
  BUSINESS_SUB_SCOPE: "Business Sub Scope",
  BUSINESS_INQUIRY: "Business Inquiry",
  BUSINESS_SCOPE_REQUIRED_TEXT: "Business Scope is Required!",
  BEAROLE_VALUES_TIME: "Orchestrate your project",
  BEAROLE_OFFERS_MORE: "Bearole offers more than just matching.",
  BE_MORE_PATIENT: "But please, be more patients designer normally apply at closing date",
  BEST_REGARDS: "Best Regards",
  // END OF B

  CAPTURED_VIEW: "Captured View",
  CANCEL_TEXT: "Cancel",
  CANDIDATES_TEXT: "Candidate",
  CATEGORY_TEXT: "All Categories",
  CERTIFICATE_TEXT: "Certificate",
  CITY_TEXT: "City",
  CLAIM_PAYMENT_TEXT: "Claim / Payment",
  COMPLETED_TEXT: "Completed",
  COMPLETED_PROJECTS: "Completed Projects",
  CONTENTS_TEXT: "Contents",
  CONFIRM_TEXT: "Confirm",
  CONFIRM_CONTEST: "Contest Confirmation!",
  CONFIRM_PROJECT: "Contest Confirmation! ",
  CONFIRM_MILESTONE: "Milestone Confirmation!",
  CONFIRM_INOFFICE: "Office Work Confirmation!",
  CONFIRM_HOURLY: "Hourly Confirmation!",
  CONSULTANT_TEXT: "Consultant",
  CONTEST: "Contest",
  CONTEST_DETAIL: "Contest Detail",
  CONTEST_OPEN: "Contest Open",
  CONTEST_DESIGN: "Post Contest Design",
  CONTEST_TITLE: "Contest Title",
  CONTEST_FOR_DESIGN_WORK: "Contest for Design Work", 
  CONTACT_PERSON: "Contact Person",
  CONTACT_US: "Contact Us",
  CLIENT_INFO: "Client Information",
  CONTACT_FIRST_NAME_REQUIRED_TEXT: "Contact first name is Required!",
  CONTACT_LAST_NAME_REQUIRED_TEXT: "Contact last name is Required!",
  CLICK_TO_SEE_TERMS: "Click to read all terms and conditions",
  CLICK_TO_SEE_TERMS_READ_MORE: "Click to read all terms and conditions",
  CLICK_TO_SEE_TERMS_BOX_CHECK: "Please, the above link to read all terms and conditions and check the box if you have read and agreed to the terms and conditions herein",
  CLICK_JOIN_TEAM: "Click here to join a great team!.",
  CLICK_HERE_TO_SETUP: "Click Here to setup",
  COMMUNITY: "Community",
  COMPANY_OR_TEAM: "Company or Team",
  CHANNEL: "Channel",
  CHAT_TEXT: "Chat",
  COMMUNICATION_MANAGER: "Communication Manager",
  COUNTRY_TEXT: "Country",
  COUNTRY_CODE: "Country Code",
  COUNTRY_REQUIRED_TEXT: "Country is Required!",
  COUNTRY_CODE_REQUIRED_TEXT: "Country Code is Required!",
  CONTRACT_HISTORY: "Contract History",
  CONTRACT_NO: "Contract No.",
  CREDIT_CARD_TEXT: "Credit Card",
  CREATE_A_NEW_POST: "Create a new post",
  CREATE_A_FREELANCER_INDIVIDUAL_ACCOUNT: "Register an Individual Account",
  CREATE_A_HEAD_HUNTER_ACCOUNT: "Register as Headhunter ",
  CREATE_FREELANCER: "Create Freelancer",
  CUSTOMER_SERVICE: "Customer Service",
  CLIENT_REGISTRATION: "Client Registration",
  CLIENT_SETTINGS: "Client Settings",
  CLICK_HERE_SEE_MORE: "Click here to see more",
  CREATE_AN_ACCOUNT: "Create a New Account",
  CREATE_NEW_MILESTONE: "Create New Milestone",
  CREATE_NEW_OFFER: "Create New Offer",
  COMPANY_NAME: "Company Name",
  CONTRACT_OFFER_TEXT: "Contract Offers",
  CONTEST_PROMOTED: "Promoted",
  CONTEST_FEATURED: "Featured Contest",
  CONTEST_FEATURED_DES:
    "Your contest will be prominently featured in the top of the contest list as well as on the Home page! It means that you will receive up to 40% more designs!",
  CONTEST_BLIND: "Blind",
  CONTACT_INFORMATION: "Contact information",
  CONTEST_STEP_TITLE_1: "Write your contest title",
  CONTEST_STEP_TITLE_2: "Select your favorite design",
  CONTEST_STEP_TITLE_3: "Describe your project",
  CONTEST_STEP_DESC_1: "Write to express the best title of your project",
  CONTEST_STEP_DESC_2: "Select to express the best Design of your project",
  CONTEST_STEP_DESC_3: "Write to express the best Description of your project",
  CONTEST_STEP_TITLE_4: "Design Preference",
  CONTEST_STEP_DESC_4:
    "Select to express the best Design preference of your project",
  CLASSIC: "Classic",
  COMPLEX: "Complex",
  COMPANY_REGIST: "Company Registration",
  CONCRETE: "Concrete",
  CONTINUE_AS_CLIENT: "Continue as a client",
  CLAIM_TEXT: "Claim",
  CLIENT_CITY: "Client City",
  CLIENT_REGISTRATION: "Client Registration",
  CLIENT_REGISTRATION_EXPLAIN: "Please, try to write more information it, will attract more talents",
  COMPANY_REGISTRATION_EXPLAIN: "Please, try to write more information it, will attract more talents",
  CONDITION_TEXT: "Condition",
  CREATE_OFFER_DETAIL:
    "This is to create a public offer. You can create a offer to the specific users by selecting user ID on the top of right from all freelancers or from the list on the talent search page under full time jobs menu. You will receive applications for full time positions only",
  CREATE_OFFER_LABEL: "Accept candidates only from the same country",
  CREATE_OFFER_LABEL_1: "and the same state, province, or city", 
  COMPANY_LOGO: "I need a company logo",
  COMPANY_LOGO_TEXT: "Company Logo",
  COMPANY_LOGO_REQUIRED: "Company logo is Required.",
  CONTEST_WILL_BE_CLOSED: "The contest will be closed with 4 days",
  CURRENCY_REQUIRED_TEXT: "currency is Required!",
  CONTINUE_TEXT:"Continue",
  CURRENT_STATUS: "Current Status",
  // END OF C

  DAYS_TEXT: "Days",
  DASHBOARD: "Dashboard",
  DAYS_LEFT: "days left",
  DAYS_PASSED: "days passed",
  DESCRIBE_YOUR_PROJECT: "Describe your project",
  DESCRIBE_YOURSELF_ORGANIZATION: "Describe the best of yourself or organization in short",
  DESCRIBE_YOUR_PROJECT_SUB:
    "Write to express the best Description of your project",
  DEPARTMENT_TEXT: "Department",
  DESCRIBE_REQUIRED_TEXT: "Description is Required!",
  DESIGN_CONTEST: "Post a Design Contest",
  DESIGN_CONTEST_step2: "Post Design Contest - Options",
  DESIGN_PREFERENCE: "Design Preference",
  DESIGN_TEXT: "Design",
  DEACTIVATE_TEXT: "Deactivate",
  DONT_ADD_HOURLY_RANGE: "Don't add an hourly range",
  DISPUTE: "Dispute",
  DRAG_YOUR_FILE: "drop your job or project description file",
  DUE_DATE: "Due Date",
  DISPUTEANDCLAIMS: "Disputes & Claims",
  DISPLAY_LIST_TEXT: "Display",
  DESCRIPTION: "Description",
  DRY_PLATE_SIGN_BOARD: "Dry plate sign board",
  DESIGNS: "30 Designs",
  DAYS_OF_WORK: "Days of work",
  DOCUMENT_TYPE_REQUIRED: "Document Type is Required!",
  DAILY_PAYMENT_FROM: " Daily Payment From",
  DON_NOT_HAVE_PROPOSAL: "Sorry! You don't have any proposals yet",
  Daily_Payment_UP_TO: "Daily Payment Up To",
  DAILY_RATE: "Daily Rate",
  DESKTOP_DOWNLOAD: "Desktop Download",
  DO_YOU_HIRE_PEOPLE: "Do you hire people to do a job that takes 2-3 hours a day?",
  DESIGN_TO_HEADHUNTER: "From design to headhunter, it is possible to generate income in a variety of fields that are capable of part-time or daily work.",
  DECLINE_INTERVIEW: "Decline Interview",
  DUTY_OF_WORK: "Duty of Work",
  // END OF D

  EDIT_FREELANCER: "Edit Freelancer",
  EACH_TEXT: "each",
  EDIT_ORGANIZATION_COMPANY: "Edit Organization (Company)",
  EDIT_ORGANIZATION_AGENCY: "Edit Organization (Agency)",
  EDIT_ORGANIZATION_DETAILS: "Edit Organization Details",
  ENGLISH: "English",
  ENGINEERING_TEXT: "Engineering",
  END_SOON: "End Soon",
  EVALUATION: "Evaluation",
  EXTEND_DUE_DATE: "Extend Due Date",
  EMPLOYEE_INFORMATION: "Employee information",
  EMAIL: "Email",
  EDUCATION: "Education",
  EDUCATION_TEXT: "Education",
  ERROR_REGIST_ACCOUNT_TEXT: "Error while registering your account, Try again.",
  ERROR_UPDATE_ACCOUNT_TEXT: "Error while update your account info, Try again.",
  ERROR_UPLOADING_IMAGE_TEXT: "Error uploading image.",
  ENTER_SELF_INTRO: "Enter Self Introduction",
  EXTRA_SERVICES: "Extra Services",
  EX_JOHN: "ex) john",
  EX_CARRY: "ex) Carry",
  EXCEL_BULK_LOAD: "Excel Bulk load",
  // END OF E
  
  FIRST_AWARDS_TEXT: "1st Award",
  FEEDBACK: "Feedback & Claims",
  FEATURED_CONTESTS_TEXT: "Featured Contests",
  FIRST_NAME: "First Name",
  FLEXIBILITY_FIRST:
  "시간제 그리고 상주업무 또는 이를 혼합하여 업무를 협의할수 있습니다.",
  FLEXIBILITY_SECOND:
  "외부 프리랜서는 물론 기존의 근무자를 본 시스템에 적용하여 유연하게 재택근무와 내부근무를 동시에 관리할수 있습니다.",
  FLEXIBILITY_TITLE: "More Flexibility",
  FREELANCER_PROFILE: "Freelancer Profile",
  FREE_CONTRACT: "Free Contract",
  FROM_AMOUNT: "From Amount",
  FREELANCER: "Freelancer",
  FREELANCER_REGISTRATION: "Freelancer Registration",
  FREELANCER_REGISTRATION_EXPLAIN: "Please, try to write more information it, will attract more talents",
  FEMALE: "Female",
  FULL_TIME_JOBS: "Full Time Jobs",
  FULL_TIME_POSITION: "For Full Time Position",
  FINAL_WINNERS: "Final Winners",
  FIND_AND_MATCH_PROJECT: "Do you know who is working for your project?",
 // END OF F
  
  GUARANTEED: "Guaranteed",
  GUARANTEED_DETAIL:
    "Guaranteed design contest means more designs and more creativity, but no refund.",
  GUARANTEED_DETAIL_DES_1:
    "By choosing this option, you’re letting designers know that you’re all in and fully committed to choosing a design. You won’t be able to request a refund but you will:",
  GUARANTEED_DETAIL_DES_2: "Have more designers participating",
  GUARANTEED_DETAIL_DES_3: "Receive 50% more designs on average",
  GUARANTEED_DETAIL_DES_4: "Get a wider range of creativity",
  GUARANTEED_DETAIL_TITLE_DESCRIPTION: "Description",
  GUEST: "Guest",
  GO_TO_FREELANCER: "Go to Freelancer",
  GO_TO_MAIN_PAGE: "Go to main page",
  // END OF G
  
  HEADHUNTER_TEXT: "Headhunter",
  HEADHUNTING_MANAGER: "Headhunting Manager",
  HEADHUNTER_REGISTRATION: "Headhunter Registration",
  HEADHUNTER_REGISTRATION_EXPLAIN: "Please, try to write more information it, will attract more talents",
  HELP_CENTER: "Help Center",
  HELP_DETAIL: "Help Center",
  HIGH_BUDGET: "High Budget",
  HOME_PAGE_TEXT: "Homepage",
  HOW_IT_WORKS: "How it works",
  HOURLY_TEXT: "Hourly",
  HOURLY_REPORT: "Hourly Report",
  HOUR_TO: "/Hour to",
  HOW_TO_POST_PROJECT: "How to post a project",
  HOW_TO_POST_PROJECT_SUB: "Bearole.com has more various project types to reflect your needs,  not only including traditional project types such as hourly and milestone project types but also an office work and a free contract type which gives more flexible ways of contract and reflects the real worl to fit your needs",
  HOW_TO_REGISTER_A_FREELANCER: "How to register a freelancer",
  HOW_TO_REGISTER_A_HEADHUNTER: "How to register a headhunter",
  HOW_TO_TO_CLAIM: "How to claim",
  HOW_TO_REGISTER_A_FREELANCER_TITLE_CONTENTS_1: 
  "Bearole.com offers two kinds identities to work as a freelancer to avoid inconveniences of existing plaforms.",
  HOW_TO_REGISTER_A_FREELANCER_TITLE_CONTENTS_2: 
  "It reflects the real world as a freelancer can work individually or as a member of an orgnization without affecting personal profile and incomes",
  HOW_TO_REGISTER_AN_INDIVIDUAL_FREELANCER: "How to register an individual freelancer",
  HOURLY_WORK: "Hourly Work",
  HOURLY_VIEW: "Hourly View",
  HOWEVER_TAKE_MORE_TOO_MANY_INQUIRY: "However, sometimes it might take more if too many inquiries",
  HIRE: "Hire",
  HIRE_COMPANY: "Hire Company",
  HIRE_FREELANCER: "Hire Freelancer",
  HOURLY_RATE: "Hourly Rate",
  HOURLY_RATE_UP_TO: "Hourly Rate Up To",
  HOURLY_RATE_FROM: "Hourly Rate From",
  HOW_WOULD_LIKE_TO_START: "How would like to start today?",
  // END OF H
  
  INTERNATIONAL_TRADE: "International Trade",
  INDIVIDUAL_TEXT: "Individual",
  IN_OFFICE: "Office Work",
  IN_ORDER_OF_EDU: "In Order of Education",
  INFO_SAVED_SUCCESS_TEXT: "Your information saved successfully!",
  INFO_UPDATED_SUCCESS_TEXT: "Your information updated successfully!",
  INTRODUCTION_TEXT: "Introduction",
  INTRODUCTION_TITLE_TEXT: "Introduction Title",
  INTRO_VIDEO_BUTTON: "Introduction Video",
  INVITATIONS_OFFERS: "Invitations & Offers",
  INVITATIONS_TEXT: "Invitations",
  INVOICE: "Invoice",
  INVOICE_DETAIL: "Invoice Detail",
  IMAGE_TEXT: "Image",
  IMAGE_UPLOADING_SIZE_TEXT: "Please select a file size of less than 1 MB.",
  I_AM_A_HEADHUNTER: "I am a headhunter",
  IT_EXPERT: "IT Expert",
  IT_EXPERT_TITLE: "IT Expert Adviser",
  IT_EXPERT_BODY:
    "A professional consultant will be assigned to your project. Person in charge with basic knowledge in the relevant field Assignment helps to place experts and uploads projects to more freelancers.",
  INTERESTING_PROJECTS: "Interesting Project",
  INVITATION_FROM_CLIENT: "You have invitation from clients",
  ISSUED_BY: "Issued By",
  INVITE_TEXT: "Invite",
  // END OF I

  JAPANESE: "日本語",
  JOBS_NEARBY: "Jobs Nearby",
  JOB_DESCRIPTION: "Job Description",
  JOB_TITLE: "Job Title",
  JOB_SUCCESS_SCORE: "Min. Job Success Score",
  JOB_POST_SUMMARY: "JOB POST SUMMARY",
  JUNGLEWORKS_BETTER: "is better and trust worth?",
  JOIN_CLIENT: "Register as client",
  JOIN_FREELANCER: "Join Freelancer",
  // END OF J
  
  KOREAN: "한국어",
  KYC_PHOTO_REQUIRED: "KYC Photo  is Required!",
  KYC_PROVE_PHOTO: "KYC Prove Photo",
  KYC_EXPLAIN_TEXT: "Please, provide a photo of you holding your ID and make sure your face is clearly visible and that all details and clearly readable.",
  // END OF K

  LANGAUGE: "Language",
  LANGUAGE_TEXT: "Language",
  LANGUAGE_LEVEL: "Language Level",
  LANGUAGE_LEVEL_BEGINNER: "Beginner",
  LANGUAGE_LEVEL_INTERMEDIATE: "Intermediate",
  LANGUAGE_LEVEL_ADVANCED: "Advanced",
  LANGUAGE_LEVEL_NATIVE: "Native",
  LAST_ACTIVITY: "Last Activity",
  LAST_NAME: "Last Name",
  LATEST_ORDER: "Latest Order",
  LEVEL_RESULT: "Level/Result",
  LESS_THAN_2: "Less than 2 years",
  LESS_THAN_3: "Less than 3 years",
  LESS_THAN_5: "Less than 5 years",
  LESS_THAN_10: "Less than 10 years",
  LOCATION_TEXT: "Location",
  LEGAL_ASSITANCE: "Legal Assistant",
  LOGO_CONTEST: "Logo Contest",
  LOGIN: "Login",
  LOW_BUDGET: "Low Budget",
  LIFE_CYCLE_1: "I have an idea",
  LIFE_CYCLE_2: "Design is ready",
  LIFE_CYCLE_3: "System Setup",
  LIFE_CYCLE_4: "Specification",
  LIFE_CYCLE_5: "Refactoring",
  LOGOUT: "Logout",
  Logo_BRAND: "Logo brand",
  LOGO_PACKAGE_TYPE: "Logo Package Type",
  LANGUAGE_PROFICIENCY: " Language Proficiency",
  LUXURY: "Luxury",
  LOOKING_FOR: "Are you looking for an office worker? No more worrying about uneasy non-face-to-face work and excessive spending.",
  // END OF L

  MARKETING_TEXT: "Marketing",
  MATCHED_TEXT: "Matched",
  MAX_FILE_SIZE: "You may attach up to 5 files of",
  MANAGEMENT_RATE: "Management Rate",
  MAX_WEEKLY_LIMIT: "Max Hourly Limit Per Week",
  MANUAL_TIME_ADDED: "Manual time successfully added",
  MEMBERSHIP_TEXT: "Membership",
  MILESTONE_TEXT: "Milestone",
  MILESTONE_VIEW: "Milestone View",
  MILESTONE_REPORT: "Milestone Report",
  MILESTONE_PAYOUT: "Milestone Payout",
  MIN_NO_OF_STAR: "Min. No. of Star",
  MIN_NO_ATTENDING_DAYS: "Attending Days Per Week",
  MIN_AMOUNT_PER_DAY: "The Amount of Daily Pay",
  MIN_REQUIREMENT_FOR_FREELANCER: "Requirements for Freelancer",
  MOBILE_NO: "Mobile No.",
  MOBILE_NO_REQUIRED_TEXT: "Mobile number is Required!",
  MY_CLIENT: "My Client",
  MY_CREDIT: "My Credit",
  MY_COUPON: "My Coupon",
  MY_CONTEST: "My Contests",
  MY_CONTEST_TEXT: "My Contest",
  MY_FREELANCERS: "My Freelancers",
  MY_PROJECT: "My Project",
  MY_INFO_TEXT: "My Info",
  MY_CONTRACTS: "My Contracts",
  MY_PROPOSAL: "My Proposals",
  MY_OFFERS: "My Offers",
  MY_OFFER: "My Offer",
  MY_REGION: "My Region",
  MY_REPORTS: "My Report",
  MUST_BE_GREATER_THAN: "Field must be greater than initial!",
  MOBILE: "Mobile",
  MATTERID_PREMIER: "Matterid Premier",
  MIN_AMOUNT_PER_DAY: "Min Amount Per Day",
  MAX_AMOUNT_PER_DAY: "Max Amount Per Day",
  MALE: "Male",
  MEMBERS_TEXT: "Members",
  MODERN: "Modern",
  MATURE: "Mature",
  MY_APPLICATIONS: "My Applications",
  MY_TALENT_TEXT: "My Talent",
  MILESTONE_BUDGET: "Project Budget For Milestone",
  MAXIMIZE_WORK_EFFICIENCY: "Find your local and global freelancers here.",
  // END OF M

  NOT_A: "Nondisclose",
  NO_OF_FREELANCER: "No. of Freelancers",
  NDA_TEXT: "NDA",
  NEXT_TEXT: "Next",
  NEXT_DAUM: "Next",
  NEED_EXTRA_HELP: "Need Extra Help?",
  NEED_TEAM_WORK: "Need a team work?",
  NUMBERS_OF_1: "1 Person",
  NUMBERS_OF_2: "2 People",
  NUMBERS_OF_3: "3 People",
  NUMBERS_OF_4: "4 People",
  NUMBERS_OF_5: "5 People",
  NUMBERS_OF_MORE: "More than 5",
  NO_MEMBERS_EXISTS_YET: "No members exists yet!",
  NO_FREELANCER_EXISTS_YET: "No freelancer exists yet!",
  NO_TEXT: "No",
  NO_COUNTRY: "No Country Found",
  NO_CITY: "No city",
  NO_ONE_TEXT: "1 Person",
  NO_TWO_TEXT: "2 Persons",
  NO_THREE_TEXT: "3 Persons",
  NO_FOUR_TEXT: "4 Persons",
  NO_FIVE_TEXT: "5 Persons",
  NO_MORE_THAN_FIVE_TEXT: "More than 5",
  NO_TEN_TEXT: "10 Hours",
  NO_TWENTY_TEXT: "20 Hours",
  NO_THIRTY_TEXT: "30 Hours",
  NO_FOURTY_TEXT: "40 Hours",
  NO_FIFTY_TEXT: "50 Hours",
  NO_UNLIMITED_TEXT: "Unlimited",
  NO_OF_EMPLOYEES: "No.of Employees",
  NO_INVITATION_EXIST_YET: "Sorry no invitation exist yet !",
  NORMALLY_DESIGNERS_LAST_MOMENT: "Normally designers tend to submit their works at the last moment.",
  NAME: "Name",
  NO_OF_CONTRACT_MADE: "   No. of Contract Made",
  NOTE_PLEASE_BE_PATIENT: "Please be more patient normally applicants upload their on last due date",
  NO_CANDIDATE: "Sorry! you have no candidate yet but ",
  // END OF N 
  
  ONGOING_PROJECT: "Ongoing Project",
  Over_10: "Over 10 years",
  OR_NEW_ADDRESS_DIFFERENT_ADDRESS: "or register the new address or different office address",
  OFFER_DETAIL: "Offer Detail",
  OFFER_OVERVIEW: "Write a Offer overview",
  ORGANIZATION_REGISTRATION: "Organization Registration",
  ORGANIZATION_NAME: "Organization Name",
  Offered_Milestone: "Offered Milestone",
  OFFER_VALID: "Offer Valid",
  OFFICE_PHOTO: "Office Photo",
  OFFICE_PHOTOS: "Office Photos",
  OFFICE_ADDRESS: "Office Address",
  OFFICE_PHOTO_UPLOAD: "Upload Office Photo",
  OTHERS_TEXT: "Others",
  OPT_INFO_EXPLAIN_TEXT: "You may skip for any of below sections if not applicable.",
  OPT_INFO_TEXT: "Optional Information",
  // END OF O 
  
  PHOTO_VIDEO: "Video/Photo Edit",
  PACKAGE_DESIGN: "Package Design",
  PACKAGE_DESIGN_DETAIL: "Package Design Detail",
  PACKAGE_TYPE: "Package Type",
  PAYMENT_INFO: "Payment Info",
  PAYMENT_METHOD: "Payment method",
  PAYING_BY_POINT:
    "Paying by Jungle point will give 5% extra bonus to freelancer!",
  PEOPLE_TEXT: "people",
  PLEASE_SELECT_ONE: "Please select at least one!",
  PORTFOLIO_TEXT: "Portfolio",
  PAID_TOTAL_TEXT: "Paid Total",
  PORTFOLIO_BUTTON_TEXT: "Add your portfolio",
  POST_A_PROJECT: "Post a project",
  PAYMENT_CONFIRMATION_TYPE: "Payment Confirmation",
  PAYMENT_VERIFIED: "Payment Verified",
  PLANNING: "Writing",
  PLEASE_SELECT_ENTITY: "Please, select one of the entities you work",
  PLEASE_ENTER_QUETIONS: "Please, enter your question here.",
  PLEASE_READ_INQUIRY: "Please, read this before making an inquiry!",
  PLEASE_MORE_PATIENT: "Please, be a bit more patient.",
  PREV_TEXT: 'PREV',
  PREFERRED_DESIGN: "Preference",
  PRIVATE_TEXT: "Private",
  PREFERRED_FREELANCER_TYPE: "Preferred Freelancer Type",
  PROFESSIOANL_AREA: "Professional Area",
  PROFESSION_TEXT: "Profession",
  PROJECT: "Project",
  PROJECT_PERIOD: "Project Period",
  PROJECT_TITLE: "Project Title",
  PROJECT_TYPE: "Project Type",
  PROJECT_BLOG: "Project Inquiry",
  PROJECT_BUDGET: "Project Budget",
  PROJECT_NO: "Project No.",
  PROJECT_DETAIL: "Project Detail",
  PROJECT_POST_MILESTONE: "Post Project - Milestone",
  PROJECT_POST_HOURLY: "Post Project - Hourly",
  PROMOTION_TEXT: "Promotion",
  PROPOSALS_TEXT: "PROPOSALS",
  PRIVATE_CONTEST: "PRIVATE CONTEST",
  PRICING_TEXT: "Pricing",
  PRIVATE_CONTEST_DETAIL:
    "Requires designers to sign a confidentiality agreement (use our NDA or upload your own)",
  PRIVATE_CONTEST_DES_1:
    "By choosing this option, your design contest won’t be visible outside of Bearole.com.",
  PRIVATE_CONTEST_DES_2:
    "Keeps your contest and designs out of Google (and other) search engine results",  
  POST_CODE: "Post Code",
  POST_A_PROJECT: "Post a Project",
  POST_NEW_PROJECT: "Post New Project",
  POST_DESIGN_CONTEST_TITLE: "Post Design Contest",
  POST_A_PROJECT_HOURLY: "Post a Project [Hourly]",
  POST_A_PROJECT_MILESTONE: "Post a Project [Milestone]",
  POST_A_PROJECT_INOFFICE: "Post a Project [Office Work]",
  POST_A_PROJECT_PROPOSAL: "Submit Your Proposal",
  PROJECT_PROPOSAL_DETAIL: "Project Proposal Detail",
  PROJECT_PROPOSAL: "Project Proposal",
  PROJECT_BLOG_TEXT: "Project Blog",
  POST_A_JOB: "Post a Job",
  POST_A_NEWJOB_FULL_TIME: "POST A NEW JOB FOR A FULL TIME POSITION",
  POWERFUL_SECURITY_TITLE: "Powerful Security on file management",
  POWERFUL_SECURITY_FIRST:
    "유료사용자의 경우 베어롤가 등록한 특허기능으로 지정된 중요한 파일은 재택 근무시에도 지정컴퓨터 이외에서는 오픈과 공유가 불가능합니다.",
  POWERFUL_SECURITY_SECOND:
    "모바일 메신저의 경우 업무용과 개인용 메신저 구별하고 업무마감시 근무자의 개인 사생활이 철저히 보호됩니다.",
  PROJECT_SEARCH: "Contest Search",
  PRINT_NOTICE: "Print notice",
  PPT_DESIGN: "PPT design",
  PROCEED_TEXT: "Proceed",
  PROFILE_HOURLY_RATE: "Profile Hourly Rate",
  PROFILE_HOURLY_RATE_REQUIRED: "Profile Hourly Rate is Required!",
  PROFILE_DAILY_RATE: "Profile Daily Rate",
  PROFILE_DAILY_RATE_REQUIRED: "Profile Daily Rate is Required!",
  PROFILE_RATE: "Profile Rate",
  PROBATION_PERIOD: "Probation Period",
  PROJECT_INFORMATION_DRAFT: "Project Information - Draft",
  PROJECT_DETAILS: "Project Details",
  PROPOSE: "Propose",
  POSITION: "Position",
  POSITIONS_TEXT: "Positions",
  POSITION_AVAILABLE: "Position Available",
  positionAvailableDate: "Position Available Date",
  PER_HR: "hr",
  PER_DAY: "day",
  PUBLIC: "Public",
  PER_HR: "hr",
  PER_DAY: "day",
  POST_PROJECT: "Post Project",
  PUBLISH_TEXT: "Publish",
  PROMOTED_CONTEST_DES:
  "  Promote your project within our social channels of more users, attract more designers for the best results. Includes Facebook, Twitter, LinkedIn and Google+.",
  POSSIBLE_TO_OUTSOURCE: "However, it is now possible to outsource tasks that are difficult to outsource through Bearole, which can be converted into hourly tasks.",
  POST_FULL_JOB_TEXT:"Post a new job For a Full Time position",
  // END OF P
  
  QUALIFICATION_TEXT: "Qualification",

  // END OF Q

  REAL_ESTATE: "Real Estate",
  REPORTS: "Reports",
  REPORT_BUG: "Report a Bug",
  REAL_ESTATE: "Real Estate",
  RECEIVE_THIS_EMAIL: "I want to receive this email",
  RESUME_ENTRY_HEAD: "Resume Entry for Headhunter",
  RESUME_SUMMARY: "Resume Summary",
  REQUIRED_LANGUAGE_TEXT: "Required Language",
  REQUEST_ID: "Request ID",
  REQUEST_DATE_TIME: "Request Date Time",
  REUSING_EXISTING_A_POST: "Reusing an existing post",
  REQUIRED_MESSAGE: "Sorry! this field is required.",
  REVIEW_TEXT: "Review",
  REGISTER_A_COMPANY_ACCOUNT: "Register a Company Account",
  REGISTER_FOR_PRICING: "Register for free now!",
  ROAD: "Road",
  REQUIRED_SKILLS: "Required Skills",
  REGISTERED_SINCE: "Registered Bearole Since",    
  REGISTER_OR_LOGIN: "Register or Login",
  REGISTRATION_DATE: "Registration Date",
  REGISTER_TEXT: "Register",
  REFER_A_FREELANCER: "Refer a Freelancer",
  RECEIVING_BANK_ACCOUNT: "Receiving Bank Account",
  // END OF R
  
  SAVE_N_CONTINUE: "Save & Continue",
  SAVE: "Save",
  SCREENINING_QUESTION: "Screening questions",
  SCHOOL_NAME: "School Name",
  SET_HOULY_RANGE_INCREASE_FREELANCER: "Set hourly range to increase the engagement with freelancers",
  SELECT_BUSINESS_SCOPE: "Select a business scope",
  SELECT_YOUR_FAVIORITE_DESIGN: "Select your favorite design style",
  SELECT_YOUR_FAVIORITE_DESIGN_SUB:
    "Select to express the best Design of your project",
  SELECT_SUB_BUSINESS_SCOPE: "Select a sub-business scope",
  SELECT_PROJECTY_TYPE: "Select a project type",
  SELECT_TEXT: "Select",
  SECOND_AWARDS_TEXT: "2nd Award",
  SELECT_DESIGN_STYLE: "Select design style",
  SEARCH_ASSISTANT: "Search Assistant",
  SEOUL_TEXT: "Seoul",
  SERVICES: "Services",
  SET_HOURLY_RANGE: " Set hourly range",
  SECOND_PLACE: "2nd place",
  SET_HOURLY_BETTER:
    "Set hourly range to increase the engagement with freelancers",
  SET_PRFERRED_CLIENT: "Set Preferred Client",
  SHORTLIST_TEXT: "Short List",
  SKILLS_TEXT: "Skills",
  SIGNUP: "Sign up",
  SIGN: "Sign",
  SITE_NAME: "Bearole.com",
  SLASH_HOUR: "/Hour",
  SUBMITTED_WORKS: "Submitted Works",
  SEARCH: "Search",
  STARS: "Stars",
  STATUS_TEXT: "Status",
  SUCCESSFUL_RATIO: "Successful Ratio",
  SHOW_MORE: "show  more",
  SHOW_LESS: "show less",
  SEE_MORE_RECOMMENDED_FREELANCER: "Click to see more recommended freelancers",
  SEE_MORE_RECOMMENDED_PROJECT: "Click to see more recommended projects.",
  salaryType: "Salary Type",
  SUBSCOPE: "SubScope",
  SELECT_CURRENCY: "Select Currency",
  SIMPLE: "Simple",
  SEND_TEXT: "Send",
  SUBMIT: "Submit",
  SEARCH_ASSISTANT_TITLE: "Utilize Recruitment Assistant",
  SEARCH_ASSISTANT_BODY:
    "A professional consultant will be assigned to your project. Person in charge with basic knowledge in the relevant field Assignment helps to place experts and uploads projects to more freelancers.",
  SEARCH_ASSISTANT_BODY1:
    "We support how to use it when the project is in progress.",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_TITLE: "Boost your visibility",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_SUBTITLE: "Boost visibility",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY:
    "A professional consultant will be assigned to your project. the person in charge with the basic knowledge in the relevant field assignment helps to place experts and invite more freelancers to this project.",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY1: "IF you select all options,",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY2:
    "We'll feature your job and top talent will receive",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY3: "special discount",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY4: "to work on your project.",
  SALARY_INSTRUCTION:
    "Please, add the daily amount that you are willing to pay",
  SELECT_BUSINESS_CATEGORY: "Select business category",
  SELF_INTRO: "Self Introduction",
  SOME_ERROR_TRY_AGAIN: "Some Error occurred please try again later",
  SORRY_NOT_REGISTERED_ACCOUNT: "Sorry! You have not registered the bank account yet In order to receive your payment or pay out freelancer, you need to set up business account first to register Strip or Paypal account.",
  SUCCESSFULLY_RATE: "Successfully Rate",
  SUBJECT_TEXT: "Subject",
  // END OF S

  TALENT_SEARCH_TEXT: "Talent Search",
  TOTAL_PROJECT_BUDGET: "Total Project Budget",
  TIP_POST_PROJECT: "Tips! For Project Post",
  TARGET_COMPLETION: "Target Completion",
  TALENT_SEARCH: "Talent Search",
  TERMS_TEXT: "Terms",
  TEST_SERVICE_COST: "Test service cost you 10% of the",
  TO_TEXT: "to",
  TO_FIND_A_TALENT:  "To find a talent",
  TO_FIND_PROJECT: "To find a project",
  TOTAL_PROJECT_VALUE: "total project value...You can read more  detail here. Would like to take this service?",
  TITLE_TEXT: "My Title",
  TITLE_TEXT_PROFILE: "Title",
  TITLE_TEXT_PROFILE_REQUIRED: "Title is Required!",
  THIRD_PLACE: " 3rd place",
  THIRD_AWARDS_TEXT: "3rd Award",
  THIS_FIELD_REQUIRED: "This field is required!",
  TOTAL_TEXT: "Total",
  TO_AMOUNT: "To Amount",
  TOTAL_PROJECT_COMPLETE : "Total Projects Completed",
  TO_REGISTER_AN_HEADHUNTER: 'To register a headhunter',
  TO_REGISTER_A_COMPANY_FREELANCER: "To Register a company organization",
  TO_REGISTER_AN_INDIVIDUAL_FREELANCER: "To Register an individual Freelancer",
  TRANSACTION: "My Transaction",
  TRANSLATION: "Translation",
  TRUSTABLE_FIRST:
    "필요시 업무자의 업무내용을 외부에서 즉시 확인이 가능함으로 부족한 소통으로 인한 잘못된 업무의 방향을 즉시 수정요구가 가능하여 이에따른 시간의 낭비를 방지할수 있습니다.",
  TRUSTABLE_SECOND:
    "베어롤에 등록된 근무자의 리모트 컴퓨터에 연결되어 업무의 신뢰성을 높이고 인공지능이 근무활동을 평가하여 업무 효율을 극대화합니다. ",
  TEACHING_TEXT: "Teaching",
  TRUSTABLE_TITLE: "Trustable and Reliable",
  TWO_GREAT_NATURE: "Two great nature",
  TURRET_DESIGN: "Turret design",
  TOOLS_PROVIDEDB_BEAROLE: "With the work tools provided by Bearroll, you can hire and manage projects transparently.",
  // END OF T
  
  USER_REGISTRATION: "User Registration",
  USER_PHOTO: "User Photo",
  USER_PHOTO_REQUIRED: "User Photo is Required!",
  USER_INFO: "USER INFO",
  USER_RESUME_REGISTRATION_TEXT: "Resume Registration",
  USER_RESUME_BULK: "Upload resume in bulk",
  UPGRADE_SERVICE: "Upgrade Service",
  UPDATE_DATE: "Update Date",
  UNTIL_HIRE: "Until Hire",
  URGENT_TEXT: "Urgent",
  UPLOAD_YOURFILE: "+ Upload you file",
  UPLOAD_COMPANY_CERTIFICATE: "Upload Company Certificate",
  ULTIMATE_SOLUTION: "The Ultimate Solution for the Untact Working Environment",
  USE_REGIST_ADDRESS: "Use the registered Address",
  // END OF U
  
  VERIFY_TEXT_BUTTON: "Verify",
  VERIFY_EXPLAIN_TEXT: "You are not able to hire any talent until you verify the payment method.",
  VIDEO_CLIP_DURATION: "Video Clip Duration",
  VIEW_MORE: "View More",
  VIEW_PROFILE: "View Profile",
  VIEW_ORGANIZATION_COMPANY: "View Organization (Company)",
  VIEW_ORGANIZATION_AGENCY: "View Organization (Agency)",
  VALID_MESSAGE: "Sorry! this field is invalid.",
  VIEW_DETAIL: "View Detail",
  VIEW_RESUME: "View Resume",
  VALUE_OF_TIME: "with the peace of mind.",
  VIEW_PARTICIPANTS: "View Participants",
  VIEW_MY_POST: "View My Post",
  VIEW_MORE_JOBS: "View more jobs",
  VIEW_PASS: "View 1st pass",
  VIEW_PROJECT_DETAIL: "View Project Detail",
  VIEW_PROPOSAL_DETAIL: "View Proposal Detail",
  VIEW_IN_PDF: "View in PDF",
  // END OF V
  
  WEB_DEVELOPMENT: "Web/Software",
  WORK_AT_OFFICE: "Office Work",
  WORK_DETAIL: "Work Detail",
  WORK_WITH_MANAGER: "Manager",
  WHAT_LIFE_CYCLE: "Where are you in the lifecycle of this project?",
  WHAT_IS_HEADHUNTER: "What is the headhunter and it's role in Bearole.com and how it works?",
  WHAT_IS_HEADHUNTER_CONTENTS_1: "Headhunter in Bearole.com is a legal entity where you can invite consultants who actually find recruiting companies either within the bearole platform or outside the platform and offer the position to suitable candidates. In order to create headhunter account, you need to have a registered company and invite at least one consultant to activate the account.", 
  WEBSITE: "Website",
  WE_TRYING_GET_BACK_INQUIRY_24HOURS: "We are trying our best to get back to any of inquiries within 24 hours",
  WE_YOUR_PATIENCE_ADVANCE: "We sincerely appreciate your patience in advance",
  WINNING_AMOUNT: "Winning Amount",
  WRITE_INTRO_YOU_ORGANIZATION: "Write the introduction of yourself or organization",
  WRITE_YOUR_DESIGN_REQUIREMENT: "Write your design requirement",
  WRITE_THE_TITLE: "Write the title",
  WORK_EXPERIENCE: "Work Experience",
  WHY_TEXT: "Why",
  WRITE_CONTEST_TITLE: "Write your contest title",
  WRITE_CONTEST_TITLE_SUB: "Write to express the best title of your project",
  WEEK: "week",
  WITHDRAW_TEXT: "Withdraw",
  WORKING_TOGETHER_AS_TEAM: "and bearole.com will do away with your concerns.", 
  WHO_IS_CONSULTANT: "Who is a consultant?",
  WINNING_AMOUNT: "Winning Amount",
  // END OF W
  
  // END OF X

  YEARS_OF_EXPERIENCE: "Years of Experience",
  YES_TEXT: "Yes",
  YES_UNDERSTAND_POLICY: "Yes, I understand and agree to the Bearole Terms of Service, including the User Agreement and Privacy Policy.",
  YOUR_QUESTIONS: "Your Questions:",
  YOUNG: "Young",
  YOU_CAN_SELECT: "You can select 3 candidates",
  YOUR_NAME: "Your Name",
  YOUTUBE_LINK: "Youtube Link",
  YEAR_FROM: "Year From",
  YEAR_TO: "Year To",
  YEAR_ISSUED: "Year Issued",
  YOU_CAN_UPLOAD_3FILES: "You can upload maximum 3 files",
  YOU_MAY_UPLOAD_3FILES: "You may upload up to 3 files",
  YOU_HAVE_CONTRACT_NO: "You must have valid contract number",
  YOU_SELECT_CATEGORY: "You can select only three per category!",
  YOU_SELECT_CATE_MAX: "You can select only from two category max!",
  // END OF Y
  
  // END OF Z

};

export const MainTextKorean = {
  ABSTRACT: "추상적인",
  ABOUT_YOUR_PAYMENT: "귀하의 지불에 대해",
  ACCOUNTING_TEXT: "법무/세무",
  ACCEPT_INTERVIEW: "인터뷰 수락",
  ACTIVE_SINCE_TEXT: "활성일",
  ACTION: "추가",
  ACTION_TEXT: "동작",
  ADMIN_PASSWORD: "관리자 암호",
  ADDRESS: "주소",
  ADDRESS_TEXT: "주소",
  ADDRESS_TEXT_BUTTON: "주소를 등록해 주세요.",
  ADD_FREELANCER: "프리랜서 추가",
  ADD_MORE_SERVICES: "서비스 추가",
  ADD_REQUIRED_SKILLS: "요구되는 기술 사항",
  ADD_SECOND_THIRD_PRIZE_DES:
  " 추가 상은 디자이너가 우승할 수 있는 기회를 증가시켜 더 많은 디자이너를 끌어들입니다.",
  ADD_SCREENING_QUESTION: "프리랜서에게 사전질의를 추가하세요.",
  ADD_PHOTO: "사진 추가",
  ADDITIONAL_PROJECT_FILES: "추가 설명 파일 (선택사항)",
  ADMIN: "일반사무",
  AREA_TO_STUDY: "전공/학과",
  ALL_FREELANCERS: "전체 프리랜서",
  ALL_PROJECTS: "전체 프로젝트",
  ALL_PACKAGES: "모든 패키지",
  ALL_MY_POSTS: "전체 포스트",
  ALLOW_CHANGE_PARTICIPANTS: "참여 인원 변경 가능",
  ALLOW_FREELANCER_LOG_TIME_MANU: "필요한 경우 프리랜서가 수동으로 시간을 기록하도록 허용",
  AMOUNT_OF_WINNING: "우승자 상금",
  AND_TEXT: "그리고",
  ANNUAL_SALES: "연간 매출",
  LINKEDIN_PROFILE_URL:"링크드인 프로필 URL",
  APP_DEVELOPMENT: "앱/소프트웨어",
  APPLICANTS_TEXT: "지원자",
  APPLY_PROBATION_PERIOD: "수습기간 적용",
  ATTACH_ADDITIONAL_DESIGN:
    "별도로 선호하는 디자인 타입이 있으시면 사진을 추가하세요.",
  ATTENDANCE: "출석",
  AVAILABLE_PER_WEEK: "주간 근무 가능 시간",
  AVAILABLE_PER_WEEK_REQUIRED: "주간 근무 가능 시간을 입력해야 합니다.",
  AVAILABILITY_TEXT: "근무 가능 시간",
  AWARDS_TEXT: "상금",
  AWARD_GURANTEED: "수상 보장",
  AWARD_CERTIFICATE: "자격증명서",
  AWARD_CERTIFICATE_BUTTON: "자격증명서를 첨부하여 주세요.",
  // END OF A

  BACK: "뒤로가기",
  BANNER_MAIN_SECOND: "소중하게 생각합니다.",
  BANNER_MAIN_THIRD:
    "베어롤에서는 프로젝트의 도급 발주는 물론 시간제 고용과 재택 또는 재택과 출근의 혼용된 방법으로 업무가 가능하여  고용인에게는 업무효율의 극대화를 프리랜서에게는 시간의 가치를 제공합니다.",
  BANNER_MAIN_FORTH:
    "관리 프로그램을 활용하시면 실시간 채팅 및 파일 업무관리 관리 다양한 관리툴을 무료로 편리하게 이용하실수 있습니다.",
  BANNER_MAIN_FIRST: "베어롤는 시간의 가치를",
  BALANCE_DUE: "차감 부족액",
  BALUESTOF_IME: "베니다.",
  BEAROLE_OFFERS_MORE: "베어롤은 매칭 그 이상을 제공합니다.",
  BEAROLE_VALUES_TIME: "베어롤은 시간의 가치를 중시합니다.",
  BE_MORE_PATIENT: "그러나 일반적으로 마감일에 더 많은 환자 디자이너가 신청하십시오.",
  BEST_REGARDS: "친애하는",
  BLIND_TEXT: "블라인드",
  BLIND_DETAIL: "창의성 향상 - 디자이너가 서로의 항목을 볼 수 없도록 차단",
  BUDGET_TEXT: "예산",
  BUSINESS_INQUIRY: "사업문의",
  BUSINESS_SCOPE: "업무 영역",
  BUSINESS_SUB_SCOPE: "업무 하위 영역",
  BUSINESS_SCOPE_REQUIRED_TEXT: "업무 영역을 입력해야 합니다.",
  // END OF B

  CANCEL_TEXT: "취소",
  CANDIDATES_TEXT: "지원자",
  COMPANY_LOGO_TEXT: "회사 로고",
  CAPTURED_VIEW: "업무 사진",
  CERTIFICATE_TEXT: "자격증",
  CATEGORY_TEXT: "모든 카테고리",
  CREATE_NEW_OFFER: "채용공고 올리기",
  CHANNEL: "채널",
  CITY_TEXT: "시/도",
  CHAT_TEXT: "채팅",
  CLIENT_INFO: "클라이언트 정보",
  CLICK_TO_SEE_TERMS: "사용약관을 반드시 확인하여 주세요.",
  CLICK_TO_SEE_TERMS_READ_MORE: "전체 사용약관 확인.",
  CLICK_TO_SEE_TERMS_BOX_CHECK: "위의 링크에서 모든 이용 약관을 읽고 동의한 경우 확인란을 선택하십시오.",
  CLAIM_TEXT: "항의",
  CLAIM_PAYMENT_TEXT: "항의 / 결제",
  COMMUNITY: "커뮤니티",
  COMPANY_OR_TEAM: "회사 또는 팀",
  COMPANY_NAME: "회사명",
  COMPANY_REGIST: "회사 등록",
  COMPLETED_TEXT: "프로젝트 완료",
  COMPLETED_PROJECTS: "완료한 프로젝트",
  COMPLEX: "복잡한",
  COMPANY_LOGO: "나는 당신의 회사 로고가 필요합니다",
  COMPANY_LOGO_REQUIRED: "회사 로고가 필요합니다.",
  COMMUNICATION_MANAGER: "커뮤니케이션 매니저",
  CONCRETE: "구체적인",
  CONDITION_TEXT: "상태",
  CONSULTANT_TEXT: "컨설턴트",
  CONTACT_INFORMATION: "연락 정보",
  CONTRACT_OFFER_TEXT: "계약 요청",
  CONTEST_PROMOTED: "프로모션",
  CONTEST_FEATURED: "추천 콘테스트",
  CONTEST_FEATURED_DES:
    "귀하의 콘테스트는 콘테스트 목록 상단과 홈 페이지에 눈에 띄게 표시됩니다! 즉, 최대 40% 더 많은 디자인을 받을 수 있습니다!",
  CONTEST_BLIND: "블라인드",
  CONTACT_PERSON: "담당자 명",
  CONFIRM_TEXT: "확인하다",
  CONFIRM_CONTEST: "콘테스트 설정",
  CONFIRM_PROJECT: "프로젝트 확인!",
  CONFIRM_MILESTONE: "마일스톤 확인!",
  CONFIRM_INOFFICE: "사무실에서 확인!",
  CONFIRM_HOURLY: "시간별 확인!",
  CONTACT_US: "문의하기",
  CONTACT_FIRST_NAME_REQUIRED_TEXT: "이름은 반드시 입력해야 합니다.",
  CONTACT_LAST_NAME_REQUIRED_TEXT: "성은 반드시 입력해야 합니다.",
  CONTENTS_TEXT: "내용",
  CONTEST: "콘테스트",
  CONTEST_TITLE: "콘테스트 제목",
  CONTEST_FOR_DESIGN_WORK: "디자인 컨테스트",
  CONTEST_DETAIL: "콘테스트 상세정보",
  CONTEST_OPEN: "콘테스트 오픈",
  CONTEST_STEP_TITLE_1: "콘테스트 제목 작성",
  CONTEST_STEP_TITLE_2: "원하시는 디자인의 형태를 골라주세요.",
  CONTEST_STEP_TITLE_3: "개최 하는 콘테스트 설명해주세요",
  CONTEST_STEP_TITLE_4: "디자인 선호도",
  CONTEST_STEP_DESC_4:
    "프로젝트의 최상의 디자인 선호도를 표현하려면 선택하십시오.",
  CONTEST_STEP_DESC_1: "프로젝트와 가장 잘 어울리는 제목을 적어 주세요.",
  CONTEST_STEP_DESC_2:
    "완성도 높은 디자인 제작을 위해 가이드라인을 제시해주시는 부분입니다",
  CONTEST_STEP_DESC_3:
    "디자이너들이 참고할 수 있는 이미지와스케치, 템플릿 등의 자료가 있으시다면 파일을 첨부하여 주세요.",
  CONTEST_WILL_BE_CLOSED: "대회 4일 종료",
  CONTINUE_AS_CLIENT: "클라이언트로 계속",
  CONTRACT_HISTORY: "프로젝트 히스토리",
  CONTRACT_NO: "계약서 번호",
  COUNTRY_CODE: "국가번호",
  COUNTRY_TEXT: "국가",
  COMPANY_REGISTRATION_EXPLAIN: "더 자세하고 많은 정보입력은 더 많은 프리랜서가 회사를 선정할 수 있는 좋은 기준이 됩니다.",
  COUNTRY_REQUIRED_TEXT: "국가를 입력해야 합니다.",
  COUNTRY_CODE_REQUIRED_TEXT: "국가코드를 입력해야 합니다.",
  CLASSIC: "클래식한",
  CREDIT_CARD_TEXT: "신용카드 등록",
  CREATE_A_NEW_POST: "신규 포스트 등록",
  CREATE_A_FREELANCER_INDIVIDUAL_ACCOUNT: "개인 프리랜서 신규등록",
  CREATE_A_HEAD_HUNTER_ACCOUNT: "헤드헌터 계정 등록",
  CREATE_FREELANCER: "프리랜서 편집",
  CREATE_NEW_MILESTONE: "마일스톤 생성",
  CREATE_OFFER_DETAIL:
    "이것은 공개 제안을 만드는 것입니다. 모든 프리랜서 또는 풀타임 채용 메뉴의 인재 검색 페이지 목록에서 오른쪽 상단의 사용자 ID를 선택하여 특정 사용자에 대한 제안을 만들 수 있습니다. 정규직에 대한 지원만 받게 됩니다.",
  CREATE_OFFER_LABEL: "동일한 국가의 후보자만 수락",
  CUSTOMER_SERVICE: "고객센터",
  CLIENT_CITY: "클라이언트 도시",
  CLICK_JOIN_TEAM: "굉장한 팀과 같이 일을 하고 싶다면 당장 여기를 클릭하세요.",
  CLICK_HERE_SEE_MORE: "더 보려면 여기를 클릭하세요.",
  CLICK_HERE_TO_SETUP: "설정하려면 여기를 클릭하세요.",
  CLIENT_REGISTRATION: "클라이언트 등록",
  CLIENT_REGISTRATION_EXPLAIN: "더 자세하고 많은 정보입력은 더 많은 프리랜서가 클라이언트를 선정할 수 있는 좋은 기준이 됩니다.",
  CLIENT_SETTINGS: "클라이언트 설정",
  CURRENCY_REQUIRED_TEXT: "통화를 입력해야 합니다.",
  CONTINUE_TEXT: "계속",
  CURRENT_STATUS: "현재 상태",
  // END OF C

  DAILY_RATE: "일급",
  Daily_Payment_UP_TO: "일일 지불 최대",
  DASHBOARD: "어드민패널",
  DAYS_OF_WORK: "근무일",
  DAILY_PAYMENT_FROM: "매일 지불 시작",
  DAYS_TEXT: "일",
  DAYS_LEFT: "일 남음",
  DAYS_PASSED: "",
  DEACTIVATE_TEXT: "비활성화",
  DECLINE_INTERVIEW: "인터뷰 거절",
  DEPARTMENT_TEXT: "부서",
  DESIGNS: "30개의 디자인",
  DESIGN_CONTEST: "디자인 콘테스트",
  DESIGN_TO_HEADHUNTER: "디자인부터 헤드헌터까지 아르바이트나 일상이 가능한 다양한 분야에서 소득 창출이 가능합니다.",
  DESCRIBE_YOUR_PROJECT: "콘테스트 설명해주세요.",
  DESCRIBE_YOURSELF_ORGANIZATION: "자신 또는 회사의 장점을 간략하게 설명하세요.",
  DESCRIBE_YOUR_PROJECT_SUB:
    "디자이너들이 참고할 수 있는 이미지와 스케치등의 자료가 있으시다면 파일을 첨부하여 주세요.",
  DESCRIPTION: "설명",
  DESCRIBE_REQUIRED_TEXT: "설명란을 입력해야 합니다.",
  DESIGN_CONTEST_step2: "포스트 디자인 콘테스트 - 옵션",
  DESIGN_PREFERENCE: "선호하는 디자인 느낌",
  DESIGN_TEXT: "디자인",
  DESKTOP_DOWNLOAD: "데스크탑 다운로드",
  DOCUMENT_TYPE_REQUIRED: "문서 유형을 입력해야 합니다.",
  DISPUTE: "분쟁",
  DISPUTEANDCLAIMS: "분쟁 및 클레임",
  DISPLAY_LIST_TEXT: "목록 개수 선택",
  DONT_ADD_HOURLY_RANGE: "시간별 금액을 표기하지 않습니다.",
  DON_NOT_HAVE_PROPOSAL: "죄송합니다! 아직 지원한 프로젝트가 없습니다.",
  DO_YOU_HIRE_PEOPLE: "하루에 2~3시간이면 되는 업무를 위해서 직원을 고용하시나요?",
  DRAG_YOUR_FILE: "작업 설명서를 끌어서 첨부하실수 있습니다.",
  DRY_PLATE_SIGN_BOARD: "마른 접시 간판",
  DUE_DATE: "지원 마감일",
  DUTY_OF_WORK: "담당 업무",
  // END OF D

  EACH_TEXT: "",
  EDUCATION: "교육",
  EDUCATION_TEXT: "학력 사항",
  EMAIL: "이메일",
  EMPLOYEE_INFORMATION: "직원 정보",
  ENGINEERING_TEXT: "기술/설계",
  ENGLISH: "ENGLISH",
  END_SOON: "마감임박순",
  ENTER_SELF_INTRO: "자기 소개 입력",
  EXTEND_DUE_DATE: "마감일 연장",
  EXTRA_SERVICES: "추가 서비스",
  EVALUATION: "프로젝트 평가",
  ERROR_REGIST_ACCOUNT_TEXT: "계정을 등록하는 동안 오류가 발생하였습니다. 재시도 해주시기 바랍니다.",
  ERROR_UPDATE_ACCOUNT_TEXT: "계정을 업데이트하는 동안 오류가 발생하였습니다. 재시도 해주시기 바랍니다.",
  ERROR_UPLOADING_IMAGE_TEXT: "이미지를 업로드하는 동안 오류가 발생하였습니다.",
  EDIT_ORGANIZATION_COMPANY: "편집하다 (회사)",
  EDIT_ORGANIZATION_DETAILS: "조직 세부 정보 편집",
  EDIT_ORGANIZATION_AGENCY: "편집하다 (회사)",
  EDIT_FREELANCER: "프리랜서 편집",
  EX_JOHN: "예) 길동",
  EX_CARRY: "예) 홍",
  EXCEL_BULK_LOAD: "엑셀 대량 로드",
  // END OF E

  FIND_AND_MATCH_PROJECT: "다양한 산업 분야의 고급 화이트칼라 프리랜서와 프로젝트를 찾아 매칭하십시오. 아르바이트나 하루 일과를 장기 이정표로 삼을 수 있습니다.",
  FEEDBACK: "피드백 & 클레임",
  FEMALE: "여성타켓",
  FEATURED_CONTESTS_TEXT: "추천 콘테스트",
  FINAL_WINNERS: "최종 우승자",
  FIRST_AWARDS_TEXT: "1등 수상",
  FIRST_NAME: "이름",
  FREE_CONTRACT: "상주 및 시간제 복합",
  FROMM_AMOUNT: "최소",
  FLEXIBILITY_FIRST:
    "프로젝트별, 시간제 그리고 전체 또는 부분 상주업무 또는 이를 혼합하여 업무를 협의할수 있습니다.",
  FLEXIBILITY_SECOND:
    "외부 프리랜서는 물론 기존의 근무자를 본 시스템에 적용하여 유연하게 재택근무와 내부근무를 동시에 관리할수 있습니다.",
  FLEXIBILITY_TITLE: "업무 유연성을 제공합니다.",
  FREELANCER_PROFILE: "프리랜서 프로필",
  FREELANCER: "프리랜서",
  FREELANCER_REGISTRATION: "프리랜서 등록",
  FREELANCER_REGISTRATION_EXPLAIN: "더 자세하고 많은 정보입력은 더 많은 클라이언트가 프리랜서를 선정할 수 있는 좋은 기준이 됩니다.",
  FROM_AMOUNT: "최저금액",
  FULL_TIME_JOBS: "정규직 채용",
  FULL_TIME_POSITION: "정규직 초대",
  // END OF F

  GO_TO_FREELANCER: "프리랜서로 이동",
  GO_TO_MAIN_PAGE: "메인 페이지로 이동",
  GUEST: "손님",
  GUARANTEED: "보장",
  GUARANTEED_DETAIL:
    "보장된 디자인 콘테스트는 더 많은 디자인과 창의성을 의미하지만 환불은 불가능합니다.",
  GUARANTEED_DETAIL_DES_1:
    "이 옵션을 선택하면 디자이너에게 디자인 선택에 전념하고 있음을 알릴 수 있습니다. 환불을 요청할 수는 없지만 다음을 수행할 수 있습니다.",
  GUARANTEED_DETAIL_DES_2: "더 많은 디자이너 참여 ",
  GUARANTEED_DETAIL_DES_3: "평균 50% 더 많은 디자인 수신",
  GUARANTEED_DETAIL_DES_4: "더 넓은 범위의 창의성 확보",
  // END OF G
  
  HEADHUNTER_REGISTRATION: "헤드헌터 등록",
  HEADHUNTER_TEXT: "헤드헌터",
  HEADHUNTER_REGISTRATION_EXPLAIN: "더 자세하고 많은 정보입력은 더 많은 프리랜서가 헤드헌터를 선정할 수 있는 좋은 기준이 됩니다.",
  HEADHUNTING_MANAGER: "헤드헌팅 매니저",
  HELP_CENTER: "헬프 센터",
  HELP_DETAIL: "헬프 상세 페이지",
  HIGH_BUDGET: "높은 예산순",
  HOW_IT_WORKS: "이용방법",
  HELLO: "안녕하세요",
  HIRE_COMPANY: "고용 회사",
  HOME_PAGE_TEXT: "홈페이지",
  HOUR_TO: "/시간당 부터 최대",
  HOW_TO_POST_PROJECT: "프로젝트 등록 및 이용방법",
  HOW_TO_POST_PROJECT_SUB: "베어롤 닷컴은 전통적인 시간제와 마일스톤 업무 뿐만아니라 상주와 복합 자유계약 등 좀 더 다양한 형태의 프로젝트를 통해 실생활에서 이루어지는 계약관계를 좀 더 면밀하고 쉽게 반영 관리 할수 있습니다.",
  HOW_TO_REGISTER_A_FREELANCER: "프리랜서 등록 및 이용방법",
  HOW_TO_REGISTER_A_HEADHUNTER: "헤드헌터 등록 및 이용방법",
  HOW_TO_TO_CLAIM: "클레임 및 분쟁 해결",
  HOW_TO_REGISTER_A_FREELANCER_TITLE_CONTENTS_1: 
  "베어롤 닷컴은 업무평가가 개인 프로파일에 적용되는 불편함, 세금문제, 기타 ID도용 문제등의 불편함을 해소하기 위하여 프로그램적으로 각 개별 요소를 만들어 현실과 똑같이 반영하여 회사와 개인 프리랜서등으로 나누어 등록이가능합니다.",
  HOW_TO_REGISTER_A_FREELANCER_TITLE_CONTENTS_2:"베어롤 닷컴에서는 개인의 업무와 회사의 업무가 중복되거나 영향을 끼치지 않습니다.",
  HOW_TO_REGISTER_AN_INDIVIDUAL_FREELANCER: "개인 프리랜서 등록방법",
  HOWEVER_TAKE_MORE_TOO_MANY_INQUIRY: "단, 문의가 너무 많을 경우 시간이 더 소요될 수 있습니다.",
  HOURLY_RATE_FROM: "시간당 요금 시작",
  HOURLY_RATE_UP_TO: "최대 시간당 요금",
  HOURLY_TEXT: "시간제",
  HOURLY_RATE: "시급",
  HOURLY_REPORT: "업무 보고서 [시간제]",
  HOURLY_PER_WEEK: "주당 근무가능 시간",
  HOURLY_WORK: "시간제 업무",
  HOURLY_VIEW: "시간별보기",
  HOW_WOULD_LIKE_TO_START: "오늘은 어떤 업무를 시작하시나요?",
  // END OF H

  IT_EXPERT: "IT 전문가",
  IT_EXPERT_TITLE: "IT 전문가 고문",
  IT_EXPERT_BODY:
    "귀하의 프로젝트에 전문 컨설턴트가 배정됩니다. 해당 분야의 기본 소양을 갖춘 담당자가 배정이 되어 전문가 배치에 도움이 되며 업로드하시는 프로젝트는 더 많은 프리랜서에게 노출됩니다.",
  IN_OFFICE: "상주업무",
  IN_ORDER_OF_EDU: "경력순",
  INTERESTING_PROJECTS: "관심 프로젝트",
  INTERNATIONAL_TRADE: "무역사무",
  INTRODUCTION_TEXT: "소개글",
  INTRODUCTION_TITLE_TEXT: "소개 제목", 
  INTRO_VIDEO_BUTTON: "소개 동영상을 링크 해주세요.",
  I_AM_A_HEADHUNTER: "나는 헤드헌터입니다.",
  IMAGE_TEXT: "이미지",
  IMAGE_UPLOADING_SIZE_TEXT: "1MB 미만의 파일을 업로드 해주시기 바랍니다.",
  INDIVIDUAL_TEXT: "개인",
  INFO_SAVED_SUCCESS_TEXT: "귀하의 정보가 성공적으로 저장되었습니다.",
  INFO_UPDATED_SUCCESS_TEXT: "귀하의 정보가 성공적으로 업데이트 되었습니다.",
  INVITATION_FROM_CLIENT: "고객의 초대가 있습니다.",
  INVITATIONS_OFFERS: "내 초대장",
  INVITATIONS_TEXT: "프로젝트 참여 요청",
  INVOICE: "인보이스",
  INVOICE_DETAIL: "인보이스 상세",
  ISSUED_BY: "발행처",
  INVITE_TEXT: "초대하기",
  // END OF I
  
  JAPANESE: "日本語",
  JOB_DESCRIPTION: "구인 상세",
  JOB_TITLE: "구인 제목",
  JOBS_NEARBY: "주변 프로젝트",
  JOB_SUCCESS_SCORE: "최소 프로젝트 완성 스코어",
  JOB_POST_SUMMARY: "작업 게시물 요약",
  JOIN_FREELANCER: "프리랜서 가입",
  JOIN_CLIENT: "클라이언트로 등록",
  JUNGLEWORKS_BETTER: "왜 베어롤에서는 신뢰할수 있을까요?",
  // END OF J
  
  KOREAN: "한국어",
  KYC_PHOTO_REQUIRED: "KYC사진을 첨부해야 합니다.",
  KYC_PROVE_PHOTO: "KYC 증명 사진",
  KYC_EXPLAIN_TEXT: "귀하의 신분증을 들고 있는 사진을 얼굴이 잘 보이도록하며 신분증의 정보가 명확하게 읽을 수 있는지 확인하고 업로드 해주시기 바랍니다.",
  // END OF K

  LANGUAGE_PROFICIENCY: "언어 능력",
  LEGAL_ASSITANCE: "법률보조",
  LAST_NAME: "성",
  LATEST_ORDER: "최신",
  LEVEL_RESULT: "레벨",
  LOCATION_TEXT: "지역",
  LOGIN: "로그인",
  LOGOUT: "로그 아웃",
  Logo_BRAND: "로고 브랜드",
  LOGO_CONTEST: "로고 콘테스트",
  LOGO_PACKAGE_TYPE: "로고 패키지 타입",
  LOOKING_FOR: "회사원을 찾고 계신가요? 불안한 비대면 업무와 과도한 지출은 더 이상 걱정하지 마세요.",  
  LOW_BUDGET: "낮은 예산순",
  LANGAUGE: "언어선택",
  LANGUAGE_TEXT: "사용가능 언어",
  LANGUAGE_LEVEL: "언어 요구 수준",
  LANGUAGE_LEVEL_BEGINNER: "초급레벨",
  LANGUAGE_LEVEL_INTERMEDIATE: "중급레벨",
  LANGUAGE_LEVEL_ADVANCED: "고급레벨",
  LANGUAGE_LEVEL_NATIVE: "원어민",
  LAST_ACTIVITY: "최근활동",
  LESS_THAN_2: "2년 미만",
  LESS_THAN_3: "3년 미만",
  LESS_THAN_5: "5년 미만",
  LESS_THAN_10: "10년 미만",
  LIFE_CYCLE_1: "아이디어만 있음",
  LIFE_CYCLE_2: "디자인 제공",
  LIFE_CYCLE_3: "서버 및 기본 완료",
  LIFE_CYCLE_4: "상세 업무사항",
  LIFE_CYCLE_5: "이슈처리/리팩토링",
  LUXURY: "고급스러운",
  // END OF L

  MALE: "남성타켓",
  MATCHED_TEXT: "매칭된 전문가",
  MATURE: "성숙한",
  MANAGEMENT_RATE: "운영관리효율",
  MANUAL_TIME_ADDED: "수동으로 추가한 시간이 성공적으로 입력되었습니다.",
  MIN_AMOUNT_PER_DAY: "하루 최소 금액",
  MAX_AMOUNT_PER_DAY: "하루 최대 금액",
  MATTERID_PREMIER: "매터리드 프리미어",
  MAX_FILE_SIZE: "파일당 최대 허용 사이즈:",
  MAX_WEEKLY_LIMIT: "최대 허용 시간(주간)",
  MAXIMIZE_WORK_EFFICIENCY: "다양한 협업 툴과 관리 툴로 업무 효율성을 극대화할 수 있으며, 사무 및 비대면 업무에서 검증 가능한 툴을 제공합니다.",
  MARKETING_TEXT: "마케팅/홍보",
  MEMBERSHIP_TEXT: "맴버쉽",
  MILESTONE_TEXT: "마일스톤",
  MILESTONE_VIEW: "마일스톤보기",
  MILESTONE_REPORT: "마일스톤 보고서",
  MILESTONE_PAYOUT: "마일스톤 지급",
  MILESTONE_BUDGET: "이정표에 대한 프로젝트 예산",
  MOBILE: "변하기 쉬운",
  MOBILE_NO: "휴대폰 번호",
  MOBILE_NO_REQUIRED_TEXT: "휴대폰 번호를 입력해야 합니다.",
  MODERN: "모던한",
  MY_REGION: "내 주변 지역",
  MY_REPORTS: "내 리포트",
  MY_CLIENT: "내 클라이언트",
  MY_CONTEST: "내 콘테스트",
  MY_COUPON: "내 쿠폰",
  MY_CREDIT: "내 크레딧",
  MY_FREELANCERS: "내 프리랜서",
  MY_PROJECT: "내 프로젝트",
  MY_CONTRACTS: "내 프로젝트",
  MY_PROPOSAL: "내 지원목록",
  MY_CONTEST_TEXT: "내 콘테스트",
  MY_APPLICATIONS: "내 작업/제안",
  MY_OFFERS: "내 제안",
  MY_OFFER: "내 제안",
  MY_INFO_TEXT: "내 정보",
  MY_TALENT_TEXT: "나의 인재풀",
  MIN_NO_OF_STAR: "최소 획득한 별 수",
  MIN_REQUIREMENT_FOR_FREELANCER: "찾고있는 프리랜서의 기본설정",
  MIN_NO_ATTENDING_DAYS: "사무실 출근일수(주간)",
  MIN_AMOUNT_PER_DAY: "일당",
  MUST_BE_GREATER_THAN: "죄송합니다! 이 필드는 다음보다 커야 합니다.",
  MEMBERS_TEXT: "인원",
  // END OF M
  
  NAME: "이름",
  NEED_EXTRA_HELP: "추가 도움이 필요하세요?",
  NEED_TEAM_WORK: "팀을 이루어 작업을 하고 싶으신가요?",
  NOTE_PLEASE_BE_PATIENT: "일반적으로 지원자는 마지막 마감일에 업로드할 때까지 인내심을 갖고 기다려 주십시오.",
  NOT_A: "비공개",
  NO_COUNTRY: "해당 국가를 찾을 수 없습니다.",
  NO_CITY: "해당 도시를 찾을 수 없습니다.",
  NDA_TEXT: "비밀준수서약",
  NEXT_TEXT: "계속",
  NEXT_DAUM: "다음",
  NO_OF_FREELANCER: "필요 인원수",
  NO_TEXT: "아니오",
  NO_CANDIDATE: "죄송합니다! 당신은 아직 후보자가 없지만",
  NO_MEMBERS_EXISTS_YET: "아직 인원이 없습니다.",
  NO_FREELANCER_EXISTS_YET: "아직 프리랜서가 없습니다.",
  NORMALLY_DESIGNERS_LAST_MOMENT: "일반적으로 디자이너는 마지막 작업일에 제출하는 경향이 있습니다.",
  NUMBERS_OF_1: "1명",
  NUMBERS_OF_2: "2명",
  NUMBERS_OF_3: "3명",
  NUMBERS_OF_4: "4명",
  NUMBERS_OF_5: "5명",
  NUMBERS_OF_MORE: "5명이상",
  NO_OF_CONTRACT_MADE: "계약 건수",
  NO_OF_EMPLOYEES: "직원 수",
  NO_TEN_TEXT: "10시간 이하",
  NO_TWENTY_TEXT: "20시간 이하",
  NO_THIRTY_TEXT: "30시간 이하",
  NO_FOURTY_TEXT: "40시간 이하",
  NO_FIFTY_TEXT: "50시간 이하",
  NO_UNLIMITED_TEXT: "제한없음",
  NO_ONE_TEXT: "1명",
  NO_TWO_TEXT: "2명",
  NO_THREE_TEXT: "3명",
  NO_FOUR_TEXT: "4명",
  NO_FIVE_TEXT: "5명",
  NO_MORE_THAN_FIVE_TEXT: "5명 이상",
  NO_INVITATION_EXIST_YET: "죄송합니다. 아직 요청이 없습니다.",
  // END OF N
  
  OFFER_OVERVIEW: "제안 개요 작성",
  OFFER_VALID: "제안 유효일",
  OFFER_DETAIL: "제안 세부 정보",
  Offered_Milestone: "제안된 마일스톤",
  OFFICE_PHOTO: "사무실 사진",
  OFFICE_PHOTOS: "사무실 사진",
  OFFICE_PHOTO_UPLOAD: "사무실 사진을 첨부하여 주세요.",
  OFFICE_ADDRESS: "사무실 주소",
  OR_NEW_ADDRESS_DIFFERENT_ADDRESS: "새로운 주소 또는 다른 사무실 주소 등록",
  ONGOING_PROJECT: "진행중인 프로젝트",
  OTHERS_TEXT: "기타",
  Over_10: "10년 이상",
  ORGANIZATION_REGISTRATION: "회사 등록",
  ORGANIZATION_NAME: "회사 명",
  OPT_INFO_TEXT: "정보 선택 옵션",
  OPT_INFO_EXPLAIN_TEXT: "옵션 사항입니다. 아래의 섹션 중 해당되지 않는 경우 건너뛸 수 있습니다.",
  // END OF O 

  PAYING_BY_POINT:
    "정글포인트로 지급시 5%의 추가 보너스가 프리랜서에 지급됩니다.",
  PAYMENT_CONFIRMATION_TYPE: "지불확정 타입",
  PAYMENT_VERIFIED: "결제수단 확인됨",
  PAID_TOTAL_TEXT: "지급 총액",
  PEOPLE_TEXT: "명",
  PLANNING: "기획/글쓰기",
  PLEASE_SELECT_ENTITY: "사용자 타입을 설정하세요.",
  PLEASE_READ_INQUIRY: "문의 전 꼭 읽어주세요.",
  PORTFOLIO_TEXT: "포트폴리오",
  PORTFOLIO_BUTTON_TEXT: "포트폴리오를 첨부하여 주세요.",
  POSITION_AVAILABLE: "지원 마감일",
  POST_CODE: "우편번호",
  POST_A_JOB: "채용 정보 게시",
  POST_A_PROJECT: "프로젝트 게시",
  POST_DESIGN_CONTEST_TITLE: "디자인 콘테스트 개최",
  POST_A_PROJECT_HOURLY: "프로젝트 게시 [시간제 고용]",
  POST_A_PROJECT_MILESTONE: "프로젝트 게시 [마일스톤]",
  POST_A_PROJECT_INOFFICE: "프로젝트 게시 [상주]",
  POST_A_PROJECT_PROPOSAL: "프로젝트 제안 게시",
  POST_A_NEWJOB_FULL_TIME: "정규직을 위해 새로운 직업을 게제해주시기 바랍니다.",
  PRIVATE_CONTEST: "개인 콘테스트",
  PRICING_TEXT: "가격",
  PRIVATE_CONTEST_DETAIL:
    "디자이너가 기밀 유지 계약에 서명해야 함(저희 NDA를 사용하거나 직접 업로드)",
  PRIVATE_CONTEST_DES_1:
    "이 옵션을 선택하면 귀하의 디자인 콘테스트가 Bearole.com 외부에 표시되지 않습니다.",
  PRIVATE_CONTEST_DES_2:
    "귀하의 콘테스트 및 디자인을 Google(및 기타) 검색 엔진 결과에서 제외",
  PROJECT_POST_MILESTONE: "프로젝트 게시 - 마일스톤",
  PROJECT_POST_HOURLY: "프로젝트 게시 - 시간제",
  PROJECT_PERIOD: "프로젝트 기간",
  PROJECT_PROPOSAL_DETAIL: "프로젝트 제안 세부 사항",
  PROJECT_PROPOSAL: "프로젝트 제안",
  PROJECT_BLOG_TEXT: "프로젝트 블로그",
  PROPOSALS_TEXT: "내 지원 목록",
  POWERFUL_SECURITY_TITLE: "외부누출이 불가능한 강력한 파일관리",
  POWERFUL_SECURITY_FIRST:
    "유료사용자의 경우 베어롤가 등록한 특허기능으로 지정된 중요한 파일은 재택 근무시에도 지정컴퓨터 이외에서는 오픈과 공유가 불가능합니다.",
  POWERFUL_SECURITY_SECOND:
    "모바일 메신저의 경우 업무용과 개인용 메신저 구별하고 업무마감시 근무자의 개인 사생활이 철저히 보호됩니다.",
  PHOTO_VIDEO: "비디오/사진 편집",
  PACKAGE_DESIGN: "패키지 디자인",
  PACKAGE_DESIGN_DETAIL: "패키지 디자인 세부 정보",
  PACKAGE_TYPE: "패키지 타입",
  PAYMENT_INFO: "결제 정보",
  PAYMENT_METHOD: "지불 방법",
  PROJECT_TYPE: "프로젝트 타입",
  PER_HR: "시간",
  PER_DAY: "일",
  PRIVATE_TEXT: "개별",
  PLEASE_ENTER_QUETIONS: "질문을 입력하세요",
  PLEASE_SELECT_ONE: "최소 한가지 이상 선택해야 합니다.",
  PLEASE_MORE_PATIENT: "조금만 더 기다려 주세요.",
  PROMOTION_TEXT: "프로모션",
  PREFERRED_DESIGN: "선호 디자인",
  PROFESSIOANL_AREA: "업무분야",
  PREFERRED_FREELANCER_TYPE: "선호하는 프리랜서 형태",
  PREV_TEXT: '이전',
  PROFESSION_TEXT: "업종 분류",
  PROJECT: "프로젝트",
  PROJECT_BLOG: "프로젝트 게시판",
  PROJECT_BUDGET: "프로젝트 예산",
  PROJECT_NO: "프로젝트 번호",
  PROJECT_DETAIL: "프로젝트 세부 정보",
  PROJECT_SEARCH: "프로젝트 선택",
  PROJECT_TITLE: "프로젝트 타이틀",
  PROJECT_INFORMATION_DRAFT: "프로젝트 정보 - 초안",
  PROJECT_DETAILS: "프로젝트 세부 정보",
  PRINT_NOTICE: "공지사항 인쇄",
  PPT_DESIGN: "PPT 디자인",
  PROFILE_HOURLY_RATE: "프로필 시간당 요금",
  PROFILE_DAILY_RATE: "프로필 일일 요금",
  PROFILE_DAILY_RATE_REQUIRED: "일일 요율을 입력해야 합니다.",
  PROFILE_HOURLY_RATE_REQUIRED: "시간당 요율을 입력해야 합니다.",
  PROFILE_RATE: "프로필 요율",
  PROPOSE: "제안하기",
  PROCEED_TEXT: "진행하기",
  POST_PROJECT: "프로젝트 등록하기",
  POSITION: "위치",
  POSITIONS_TEXT: "채용공고",
  positionAvailableDate: "제안 유효일",
  PUBLIC: "대중적인",
  PROMOTED_CONTEST_DES:
    "더 많은 사용자의 소셜 채널 내에서 프로젝트를 홍보하고 최상의 결과를 위해 더 많은 디자이너를 유치하십시오. Facebook, Twitter, LinkedIn 및 Google+가 포함됩니다.",
  PUBLISH_TEXT: "게시",
  PROBATION_PERIOD: "인턴 기간",
  POSSIBLE_TO_OUTSOURCE: "그렇다고 외주를 맡기기도 어려운 업무들은 이제 베어롤을 통해 시간당 업무로 신룋 할수있는 외주업무가 가능합니다.",
  POST_FULL_JOB_TEXT:"정규직에 대한 새 작업 게시",
  // END OF P

  QUALIFICATION_TEXT: "학력",

  // END OF Q
  
  REAL_ESTATE: "부동산사무",
  RECEIVE_THIS_EMAIL: "이 이메일 주소로 메일을 받고 싶습니다.",
  REPORTS: "리포트",
  REPORT_BUG: "버그 신고",
  RESUME_SUMMARY: "이력서 요약",
  REGISTERED_SINCE: "베어롤 등록일",               
  REGISTER_A_COMPANY_ACCOUNT: "회사 계정 등록",
  REGISTER_FOR_PRICING: "지금 무료로 등록하세요!",
  REGISTER_OR_LOGIN: "등록 또는 로그인",
  REGISTER_TEXT: "등록",
  REGISTRATION_DATE: "등록순",
  RESUME_ENTRY_HEAD: "헤드헌터용 이력서등록",
  REUSING_EXISTING_A_POST: "기존 포스트를 활용",
  REFER_A_FREELANCER: "프리랜서 추천",
  RECEIVING_BANK_ACCOUNT: "은행 계좌 수취",
  REPLY_TEXT: "답변관련",
  REQUIRED_SKILLS: "필요한 기술",
  REQUIRED_LANGUAGE_TEXT: "요구 되는 언어",
  REQUIRED_MESSAGE: "죄송합니다! 이 필드는 필수입니다.",
  REQUEST_ID: "요청 ID",
  REQUEST_DATE_TIME: "요청한 날짜",
  REVIEW_TEXT: "리뷰",
  ROAD: "도로",
  // END OF R

  SAVE_N_CONTINUE: "저장후 계속",
  SAVE: "저장",
  SEND_TEXT: "보내기",
  SELF_INTRO: "자기 소개서",
  SCHOOL_NAME: "학교 명",
  SCREENINING_QUESTION: "기초 질의 사항",
  SECOND_AWARDS_TEXT: "2등 수상",
  SECOND_PLACE: "2위",
  SELECT_PROJECTY_TYPE: "프로젝트 타입을 선택하세요",
  SELECT_BUSINESS_SCOPE: "비지니스 분야를 선택하세요",
  SELECT_SUB_BUSINESS_SCOPE: "상세 비지니스 분야를 선택하세요.",
  SELECT_DESIGN_STYLE: "원하시는 디자인 형태를 선택하세요",
  SELECT_YOUR_FAVIORITE_DESIGN: "원하시는 디자인의 형태를 골라주세요.",
  SELECT_YOUR_FAVIORITE_DESIGN_SUB:
    "완성도 높은 디자인 제작을 위해 가이드라인을 제시해주시는 부분입니다.",
  SEOUL_TEXT: "서울",
  SET_HOULY_RANGE_INCREASE_FREELANCER: "시간당 범위를 증가시켜 프리랜서의 참여도를 높일 수 있습니다.",
  SEARCH_ASSISTANT: "찾기 도움이",
  SELECT_TEXT: "선택하세요",
  SERVICES: "서비스",
  SET_HOURLY_RANGE: "시간당 금액 지불의향 설정",
  SET_HOURLY_BETTER:
    "시간당 금액을 설정하시면 더 많은 프리랜서의 지원을 보실수 있습니다.",
  SET_PRFERRED_CLIENT: "선호고객으로 저장",
  SHORTLIST_TEXT: "최종 후보자",
  SITE_NAME: "베어롤 닷컴",
  SOME_ERROR_TRY_AGAIN: "일부 오류가 발생하였으니 다음에 다시 시도하여 주시기 바랍니다.",
  SKILLS_TEXT: "기술목록",
  SIGNUP: "가입하기",
  SIGN: "징후",
  SLASH_HOUR: "/시간",
  SUBMITTED_WORKS: "제출된 작업",
  SEARCH: "검색",
  STARS: "스타",
  STATUS_TEXT: "상태",
  SUCCESSFUL_RATIO: "성공률",
  SUCCESSFULLY_RATE: "성공률",
  SHOW_MORE: "자세히보기",
  SHOW_LESS: "요약보기",
  SEE_MORE_RECOMMENDED_FREELANCER: "더 많은 추천 프리랜서를 보려면 클릭하세요.",
  SEE_MORE_RECOMMENDED_PROJECT: "더 많은 프로젝트를 보려면 클릭하세요.",
  SUBSCOPE: "하위 범위",
  salaryType: "급여 유형",
  SELECT_CURRENCY: "통화 선택",
  SIMPLE: "단순한",
  SUBMIT: "제출하다",
  SUBJECT_TEXT: "제목",
  SORRY_NOT_REGISTERED_ACCOUNT: "죄송합니다! 아직 은행 계좌를 등록하지 않았습니다. 대금을 받거나 프리랜서에게 지급을 할려면 먼저 비즈니스 계좌를 설정하고 Strip 또는 Paypal 계좌를 등록해야 합니다.",
  SEARCH_ASSISTANT_TITLE: "채용 도우미를 활용",
  SEARCH_ASSISTANT_BODY:
    "귀하의 프로젝트에 전문 컨설턴트가 배정됩니다. 해당 분야의 기본 소양을 갖춘 담당자가 배정이 되어 전문가 배치에 도움이 되며 업로드하시는 프로젝트는 더 많은 프리랜서에게노출됩니다.",
  SEARCH_ASSISTANT_BODY1: "프로젝트의 진행시 사용방법등을 지원합니다.",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_TITLE: "노출 증가",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_SUBTITLE: "노출 증가", 
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY:
    "귀하의 프로젝트에 전문 컨설턴트가 배정됩니다. 해당 현장배치의 기초지식을 담당하는 담당자가 본 프로젝트에 전문가를 배치하고 더 많은 프리랜서를 초청할 수 있도록 도와줍니다.",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY1: "모든 옵션을 선택하면",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY2:
    "우리는 당신의 직업을 소개하고 최고의 재능을 받게 될 것입니다",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY3: "특별 할인",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY4: "당신의 프로젝트에 일하기 위해.",
  SALARY_INSTRUCTION: "아래는 반드시 일일 지급 금액을 입력하세요.",
  SELECT_BUSINESS_CATEGORY: "비즈니스 카테고리 선택",
   // END OF S

  TARGET_COMPLETION: "목표 완료일",
  TALENT_SEARCH_TEXT: "구인 검색",
  TERMS_TEXT: "계약 조건",
  TOTAL_PROJECT_BUDGET: "전체 프로젝트 예산",
  TIP_POST_PROJECT: "팁! 프로젝트 포스트용",
  TITLE_TEXT: "Title",
  TITLE_TEXT_PROFILE: "제목/소개글",
  TITLE_TEXT_PROFILE_REQUIRED: "제목을 입력해야 합니다.",
  TO_TEXT: "~",
  TOTAL_TEXT: "전체",
  TO_AMOUNT: "최대금액",
  TO_FIND_A_TALENT:  "전문가 찾기",
  TO_FIND_PROJECT: "프로젝트 찾기",
  TOTAL_PROJECT_COMPLETE : "완료한 프로젝트",
  TO_REGISTER_AN_HEADHUNTER: '헤드헌터 등록',
  TO_REGISTER_A_COMPANY_FREELANCER: "기업 프리랜서",
  TO_REGISTER_AN_INDIVIDUAL_FREELANCER: "개인 프리랜서",
  THIRD_AWARDS_TEXT: "3위 수상",
  THIRD_PLACE: "3위",
  THIS_FIELD_REQUIRED: "이 영역은 필수 입력란 입니다.",
  TRANSACTION: "거래내역",
  TRANSLATION: "통번역",
  TRUSTABLE_FIRST:
    "필요시 업무자의 업무내용을 외부에서 즉시 확인이 가능함으로 부족한 소통으로 인한 잘못된 업무의 방향을 즉시 수정요구가 가능하여 이에따른 시간의 낭비를 방지할수 있습니다.",
  TRUSTABLE_SECOND:
    "베어롤에 등록된 근무자의 리모트 컴퓨터에 연결되어 업무의 신뢰성을 높이고 인공지능이 근무활동을 평가하여 업무 효율을 극대화합니다. ",
  TEACHING_TEXT: "온/오프라인 강의",
  TRUSTABLE_TITLE: "신뢰성있는 근무환경을 제공",
  TWO_GREAT_NATURE: "두 개의 위대한 자연",
  TURRET_DESIGN: "포탑 디자인",
  TOOLS_PROVIDEDB_BEAROLE: "베어롤에서 제공하는 업무 툴로 투명하고 고용하고 프로젝트를 관리할수 있습니다.",
  // END OF T

  ULTIMATE_SOLUTION: "언택트 업무환경의 최적의 솔루션을 제공합니다.",
  UNTIL_HIRE: "고용시 까지",
  URGENT_TEXT: "긴급업무",
  UPLOAD_YOURFILE: "+ 파일을 첨부하세요",
  UPLOAD_COMPANY_CERTIFICATE: "회사 증명서 업로드",
  UPDATE_DATE: "업데이트 날짜",
  USER_PHOTO: "사용자 사진등록",
  USER_INFO: "사용자 정보",
  USER_REGISTRATION: "사용자 등록",
  USER_PHOTO_REQUIRED: "사용자의 사진이 필요합니다.",
  USER_RESUME_TEXT: "이력서 입력보드",
  USER_RESUME_BULK: "이력서 일괄 업로드",
  UPGRADE_SERVICE: "업그레이드 서비스",
  USE_REGIST_ADDRESS: "등록된 주소 사용",
  // END OF U
  
  VERIFY_TEXT_BUTTON: "인증하여 주세요.",
  VERIFY_EXPLAIN_TEXT: "결제 수단을 인증하기 전에는 프리랜서를 고용할 수 없습니다.",
  VIDEO_CLIP_DURATION: "클립 영상 길이",
  VIEW_MORE: "더보기",
  VIEW_MORE_JOBS: "프로젝트 더보기",
  VALID_MESSAGE: "죄송합니다! 이 필드는 유효하지 않습니다.",
  VIEW_ORGANIZATION_COMPANY: "조직보기 (회사)",
  VIEW_ORGANIZATION_AGENCY: "조직보기 (대행사)",
  VIEW_DETAIL: "상세보기",
  VIEW_PARTICIPANTS: "참가자 보기",
  VIEW_MY_POST: "내 게시물 보기",
  VIEW_PASS: "첫 번째 패스 보기",
  VIEW_PROJECT_DETAIL: "프로젝트 세부 정보 보기",
  VIEW_PROPOSAL_DETAIL: "제안 세부 정보 보기",
  VIEW_RESUME: "이력서 검색",
  VIEW_IN_PDF: "PDF로 보기",
  // END OF V
  
  WEB_DEVELOPMENT: "웹/소프트웨어",
  WHAT_LIFE_CYCLE: "현재 프로젝트의 진행 사항을 선택하세요.",
  WHAT_IS_HEADHUNTER: "베어롤 닷컴에서 헤드헌터와 그 역할은 무엇인가요?",
  WHAT_IS_HEADHUNTER_CONTENTS_1: "베어롤 닷컴에서 헤드헌터는 컨설턴트의 고용주 역할을 하며 컨설턴트를 초대하고 구인구직과 관련된 업무를 배정하고 관련 인재와 구인 회사를 등록 관련 할수 있는 하나의 가상의 회사라고 보시면 됩니다. 헤드헌터 계정을 열기위해서는 반드시 회사를 먼저 등록하셔야 합니다. 회사의 형태 즉, 주식회사나 개인회사는 관계없지만 반드시 등록된 회사가 있어야 하며 최소 업무를 수행할 1인의 컨설턴트를 등록하셔야 합니다. 대표자가 컨설턴트가 되실수도 있습니다.", 
  WE_TRYING_GET_BACK_INQUIRY_24HOURS: "문의사항에 대해 24시간 이내에 답변을 드릴 수 있도록 최선을 다하겠습니다.",
  WE_YOUR_PATIENCE_ADVANCE: "미리 양해해 주셔서 감사합니다.",
  WORK_AT_OFFICE: "상주업무",
  WORK_DETAIL: "업무상세",
  WORK_WITH_MANAGER: "담당 매니저",
  WEBSITE: "웹 사이트",
  WINNING_AMOUNT: "상금",
  WRITE_YOUR_DESIGN_REQUIREMENT: "디자인 요구사항을 작성하세요",
  WRITE_INTRO_YOU_ORGANIZATION: "자신 또는 회사에 대한 소개를 작성하세요.",
  WRITE_THE_TITLE: "제목 쓰기",
  WORK_EXPERIENCE: "직장 경험",
  WHY_TEXT: "왜",
  WINNING_AMOUNT: "당첨 금액",
  WRITE_CONTEST_TITLE: "콘테스트 타이틀작성",
  WRITE_CONTEST_TITLE_SUB: "프로젝트와 가장 잘 어울리는 제목을 적어 주세요.",
  WEEK: "주",
  WITHDRAW_TEXT: "철회하다",
  WORKING_TOGETHER_AS_TEAM: "웹과 모바일에서 그리고 데스크탑에서도 팀을 함께 업무를 함께 업무 효율성을 극대화합니다.",
  // END OF W

  // END OF X

  YOU_CAN_SELECT: "3명의 후보를 선택할 수 있습니다",
  YOU_CAN_UPLOAD_3FILES: "최대 3개의 파일을 업로드할 수 있습니다.",
  YOU_MAY_UPLOAD_3FILES: "3개의 파일을 업로드할 수 있습니다.",
  YOU_SELECT_CATE_MAX: "최대 2가지 카테고리에서만 선택할 수 있습니다.",
  YOU_HAVE_CONTRACT_NO: "반드시 유효한 계약서 번호가 있어야 합니다.",
  YES_TEXT: "네",
  YES_UNDERSTAND_POLICY: "네, 사용자 계약 및 개인 정보 보호 정책을 포함한 Bearole 서비스 약관을 이해하고 이에 동의합니다.",
  YEARS_OF_EXPERIENCE: "요구되는 최소 경력",
  YOUR_QUESTIONS: "입력하신 질문사항 :",
  YOUNG: "젊은성향",
  YOUR_NAME: "성명",
  YOUTUBE_LINK: "Youtube 링크",
  YEAR_FROM: "연도 부터",
  YEAR_TO: "연도 까지",
  YEAR_ISSUED: "발행 연도",
  YOU_SELECT_CATEGORY: "카테고리당 3가지만 선택할 수 있습니다.",
  // END OF Y

  // END OF Z
};

export const MainTextJapanese = {
  ACCOUNTING_TEXT: "法務/会計",
  WEB_DEVELOPMENT: "ウェブ/ソフトウェア",
  DESIGN_TEXT: "設計",
  CUSTOMER_SERVICE: "顧客サービス",
  TEACHING_TEXT: "オン/オフラインチュートリアル",
  INTERNATIONAL_TRADE: "国際貿易",
  ADMIN: "管理者",
  REAL_ESTATE: "不動産",
  PLANNING: "書き込み",
  TRANSLATION: "翻訳",
  ENGINEERING_TEXT: "エンジニアリング",
  PHOTO_VIDEO: "ビデオ/写真編集",
  MARKETING_TEXT: "マーケティング",
  PROJECT: "事業",
  HELLO: "こんにちは",
  DASHBOARD: "ダッシュボード",
  MY_CONTRACTS: "私のプロジェクト",
  INVITATIONS_OFFERS: "私の招待状",
  POST_A_PROJECT: "プロジェクトを投稿する",
  FREELANCER: "フリーランサー",
  WINNING_AMOUNT: "当選金額",
  ALL_FREELANCERS: "すべてのフリーランサー",
  MY_FREELANCERS: "私のフリーランサー",
  HOW_IT_WORKS: "使い方",
  CONTEST: "コンテスト",
  EDIT_FREELANCER: "フリーランサーを編集する",
  HOURLY_WORK: "時給",
  WORK_AT_OFFICE: "オフィスで働く",
  DISPUTE: "紛争",
  MY_CREDIT: "私のクレジット",
  REPORTS: "報告書",
  TRANSACTION: "トランザクション",
  MY_COUPON: "マイクーポン",
  SERVICES: "サービス",
  COMMUNICATION_MANAGER: "コミュニケーションマネージャー",
  HEADHUNTING_MANAGER: "ヘッドハンティングマネージャー",
  COMMUNITY: "コミュニティ",
  CHANNEL: "チャネル",
  HELP_CENTER: "ヘルプセンター",
  CONTACT_US: "お問い合わせ",
  LOGIN: "ログインする",
  SIGNUP: "サインアップ",
  SIGN: "サイン",
  POST_A_JOB: "仕事を投稿する",
  LANGAUGE: "言語",
  ENGLISH: "英語",
  KOREAN: "韓国語",
  JAPANESE: "日本人",
  LOGOUT: "ログアウト",
  GUEST: "ゲスト",

  CONFIRM_TEXT: "確認",
  CONTEST_PROMOTED: "プロモート",
  CONTEST_FEATURED: "注目のコンテスト",
  CONTEST_FEATURED_DES:
    "콘테스트 목록에서 배경색과 테두리가 하이라이트 되어 표시 됩니다. 보다 많은 디자이너의 눈길을 사로잡을 수 있습니다.",
  CONTEST_BLIND: "ブラインド",
  VIEW_ORGANIZATION_COMPANY: "組織の表示（会社）",
  VIEW_ORGANIZATION_AGENCY: "組織の表示（会社）",
  EDIT_ORGANIZATION_COMPANY: "編集 (회사)",
  EDIT_ORGANIZATION_AGENCY: "編集 (회사)",
  EDIT_ORGANIZATION_DETAILS: "組織の詳細を編集する",
  CONTACT_INFORMATION: "連絡先",
  EMPLOYEE_INFORMATION: "従業員情報",

  NAME: "名前",
  ADDRESS: "住所",
  MOBILE: "モバイル",
  EMAIL: "Eメール",
  WEBSITE: "ウェブサイト",
  Logo_BRAND: "ロゴブランド",
  PRINT_NOTICE: "通知を印刷する",
  ROAD: "道路",
  PPT_DESIGN: "PPTデザイン",
  MATTERID_PREMIER: "マテリアッドプレミア",
  TWO_GREAT_NATURE: "2つの素晴らしい自然",
  DRY_PLATE_SIGN_BOARD: "ドライプレート看板",
  TURRET_DESIGN: "タレットの設計",
  DESIGNS: "30のデザイン",
  SEARCH: "探す",
  SELECT_SUB_BUSINESS_SCOPE: "TODO: Select a sub-business scope",
  SAVE: "保存する",
  HOURLY_RATE_FROM: "からの時給",
  HOURLY_RATE_UP_TO: "時給",
  DAYS_OF_WORK: "仕事の日",
  DAILY_PAYMENT_FROM: "からの毎日の支払い",
  CLIENT_CITY: "クライアントシティ",
  Daily_Payment_UP_TO: "毎日の支払いまで",
  STARS: "出演者",
  SUCCESSFUL_RATIO: "成功率",
  NO_OF_CONTRACT_MADE: "契約数",
  LANGUAGE_PROFICIENCY: "言語能力",
  EDUCATION: "教育",
  FREE_CONTRACT: "상주및시간제 복합",
  APPLY_PROBATION_PERIOD: "試用期間を適用する",
  JOB_POST_SUMMARY: "求人情報の概要",
  SHOW_MORE: "もっと見せる",
  EXTRA_SERVICES: "追加サービス",
  SHOW_LESS: "表示を減らす",
  DON_NOT_HAVE_PROPOSAL: "ごめん！まだ提案はありません",
  SEE_MORE_RECOMMENDED_FREELANCER:
    "クリックして、おすすめのフリーランサーをもっと見る",
  PROJECT_NO: "プロジェクト番号",
  PROJECT_INFORMATION_DRAFT: "プロジェクト情報-ドラフト",
  PROJECT_DETAILS: "プロジェクトの詳細",
  PAYMENT_VERIFIED: "支払い確認済み",
  BUSINESS_SCOPE: "事業範囲",
  SUBSCOPE: "サブスコープ",
  JOB_TITLE: "職名",
  JOB_DESCRIPTION: "仕事内容",
  REQUIRED_SKILLS: "必要なスキル",
  PREFERRED_FREELANCER_TYPE: "優先フリーランサータイプ",
  NO_OF_FREELANCER: "フリーランサーの数",
  BUDGET_TEXT: "予算",
  MIN_NO_OF_STAR: "最小星の数",
  JOB_SUCCESS_SCORE: "最小仕事の成功スコア",
  WORK_EXPERIENCE: "実務経験",
  MUST_BE_GREATER_THAN: "ごめん！このフィールドはより大きい必要があります",
  NEXT_TEXT: "次",
  BACK: "バック",
  PROPOSE: "提案する",
  PROJECT_PROPOSAL: "プロジェクト提案",
  CREATE_A_HEAD_HUNTER_ACCOUNT: "ヘッドハンターアカウントを登録する",
  HEADHUNTER_REGISTRATION: "ヘッドハンター登録",
  REGISTER_A_COMPANY_ACCOUNT: "会社のアカウントを登録する",
  ORGANIZATION_REGISTRATION: "組織登録",
  POSITION: "位置",
  salaryType: "給与タイプ",
  positionAvailableDate: "ポジション利用可能日",
  Offered_Milestone: "提供されたマイルストーン",
  TIP_POST_PROJECT: "チップ！プロジェクト投稿用",
  OFFER_VALID: "有効なオファー",
  PER_HR: "時間",
  ALL_PROJECTS: "すべてのプロジェクト",
  PER_DAY: "日",
  MIN_AMOUNT_PER_DAY: "1日あたりの最小金額",
  MAX_AMOUNT_PER_DAY: "1日あたりの最大金額",
  SELECT_CURRENCY: "通貨を選択",
  CONTEST_STEP_TITLE_1: "コンテストのタイトルを書く",
  CONTEST_STEP_TITLE_2: "お気に入りのデザインを選択してください",
  CONTEST_STEP_TITLE_3: "プロジェクトについて説明してください",
  CONTEST_STEP_DESC_1: "プロジェクトの最高のタイトルを表現するために書く",
  CONTEST_STEP_DESC_2: "プロジェクトの最高のデザインを表現するために選択します",
  CONTEST_STEP_DESC_3:
    "あなたのプロジェクトの最高の説明を表現するために書いてください",
  CONTEST_STEP_TITLE_4: "デザインの好み",
  CONTEST_STEP_DESC_4:
    "プロジェクトの最適なデザイン設定を表現するために選択します",
  CONTEST_OPEN: "コンテストオープン",
  OFFER_VALID: "有効なオファー",
  PER_HR: "時間",
  PER_DAY: "日",
  WEEK: "週",
  MILESTONE_BUDGET: "マイルストーンのプロジェクト予算",
  DESIGN_CONTEST: "ポストデザインコンテスト",
  GUARANTEED: "保証",
  GUARANTEED_DETAIL:
    "保証されたデザインコンテストは、より多くのデザインとより多くの創造性を意味しますが、返金はありません。",
  PRIVATE_CONTEST: "プライベートコンテスト",
  PRIVATE_CONTEST_DETAIL:
    "設計者は機密保持契約に署名する必要があります（NDAを使用するか、独自にアップロードしてください）",
  PRIVATE_CONTEST_DES_1:
    "このオプションを選択すると、デザインコンテストはBearole.comの外部に表示されなくなります。",
  PRIVATE_CONTEST_DES_2:
    "コンテストやデザインをGoogle（およびその他の）検索エンジンの結果から除外します",
  ADD_SECOND_THIRD_PRIZE: "2位、3位の賞品を追加",
  ADD_SECOND_THIRD_PRIZE_DES:
    " 追加の賞は、デザイナーが勝つチャンスを増やし、したがって、より多くのデザイナーを引き付けます",
  SECOND_PLACE: "2位",
  THIRD_PLACE: "3位",
  DESCRIPTION: "説明",
  GUARANTEED_DETAIL_DES_1:
    "このオプションを選択することで、設計者に、設計の選択に全力で取り組んでいることを知らせることができます。払い戻しをリクエストすることはできませんが、次のことを行います。",
  GUARANTEED_DETAIL_DES_2: "より多くのデザイナーを参加させる",
  GUARANTEED_DETAIL_DES_3: "平均して50％多くのデザインを受け取る",
  GUARANTEED_DETAIL_DES_4: "幅広い創造性を手に入れよう",
  DESIGN_CONTEST_step2: "ポストデザインコンテスト-オプション",
  PROMOTED_CONTEST_DES:
    "고객님의 콘테스트가 리스트 최상위에 위치하게 되어 다른 콘테스트보다 더욱 많이 노출됩니다.",
  BLIND_DETAIL:
    "創造性を高める-デザイナーがお互いのエントリを見るのをブロックする",
  SUBMIT: "送信",
  AND_TEXT: "と",
  PROFILE_HOURLY_RATE: "プロファイル時給",
  PROFILE_DAILY_RATE: "プロファイルの1日あたりの料金",
  AVAILABLE_PER_WEEK: "週あたりの可用性",
  REGISTER_OR_LOGIN: "登録またはログイン",
  JOIN_FREELANCER: "フリーランサーに参加する",
  JOIN_CLIENT: "クライアントとして登録",
  GO_TO_FREELANCER: "フリーランサーに行く",
  CONTINUE_AS_CLIENT: "クライアントとして継続",
  POST_PROJECT: "プロジェクト後",
  CONDITION_TEXT: "状態",
  FULL_TIME_JOBS: "フルタイムの仕事",
  SEARCH_ASSISTANT_TITLE: "採用アシスタントを活用する",
  SEARCH_ASSISTANT_BODY:
    "プロのコンサルタントがあなたのプロジェクトに割り当てられます。関連分野の基本的な知識を持つ担当者割り当ては、専門家を配置し、より多くのフリーランサーにプロジェクトをアップロードするのに役立ちます。",
  SEARCH_ASSISTANT_BODY1:
    "プロジェクトの進行時に使用方法などをサポートします。",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_TITLE: "視認性を高める",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_SUBTITLE: "視認性を高める", 
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY:
    "プロのコンサルタントがあなたのプロジェクトに割り当てられます。関連する分野の割り当ての基本的な知識を持つ担当者は、専門家を配置し、このプロジェクトにより多くのフリーランサーを招待するのに役立ちます。",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY1: "すべてのオプションを選択した場合、",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY2:
    "私たちはあなたの仕事を特集し、トップタレントが受け取る",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY3: "特別割引",
  SEARCH_ASSISTANT_BOOST_VISIBILITY_BODY4:
    "あなたのプロジェクトに取り組むために。",
  IT_EXPERT: "ITエキスパート",
  IT_EXPERT_TITLE: "ITエキスパートアドバイザー",
  IT_EXPERT_BODY:
    "プロのコンサルタントがあなたのプロジェクトに割り当てられます。関連分野の基本的な知識を持つ担当者割り当ては、専門家を配置し、より多くのフリーランサーにプロジェクトをアップロードするのに役立ちます。",
  HOURLY_RATE: "時給",
  SALARY_INSTRUCTION:
    "あなたが支払うことをいとわない1日あたりの金額を追加してください",
  MY_APPLICATIONS: "私の仕事/オファー",
  INTERESTING_PROJECTS: "興味深いプロジェクト",
  WITHDRAW_TEXT: "撤退",
  CREATE_OFFER_DETAIL:
    "これは公募を作成することです。すべてのフリーランサーから、またはフルタイムのジョブメニューの下にあるタレント検索ページのリストから右上のユーザーIDを選択することにより、特定のユーザーへのオファーを作成できます。フルタイムのポジションの申請のみを受け取ります",
  CREATE_OFFER_LABEL: "同じ国からの候補者のみを受け入れる",
  SELECT_BUSINESS_CATEGORY: "業種を選択",
  OFFER_OVERVIEW: "オファーの概要を書く",
  PUBLISH_TEXT: "公開",
  PROBATION_PERIOD: "試用期間",
  BEAROLE_VALUES_TIME: "ベアロールは時間の価値を大切にします。",
  BALUESTOF_IME: "ベます。",
  FIND_AND_MATCH_PROJECT: "さまざまな業界のハイエンドホワイトカラーフリーランサーとプロジェクトを見つけてマッチングします。長期的なマイルストーンとして、アルバイトや日課を利用することができます。",
  MAXIMIZE_WORK_EFFICIENCY: "様々なコラボレーションツールと管理ツール業務効率を最大化することができ、事務および非対面業務で検証可能なツールを提供しています。",
  WORKING_TOGETHER_AS_TEAM: "ウェブとモバイルでそしてデスクトップでもチームを組み合わせて業務を組み合わせて業務効率を最大化します。",
  DESKTOP_DOWNLOAD: "デスクトップのダウンロード",
  BEAROLE_OFFERS_MORE: "ベアロールはマッチングそれ以上を提供しています。",
  COMPANY_LOGO: "会社のロゴが必要です",
  AWARD_GURANTEED: "賞保証",
  NOTE_PLEASE_BE_PATIENT: "通常、申請者は最終期日にアップロードするので、もっと辛抱強く待ってください",
  YOU_CAN_SELECT: "あなたは3つの候補者を選ぶことができます",
  CONTEST_WILL_BE_CLOSED: "コンテストは4日で終了します",
  NO_CANDIDATE: "ごめん！まだ候補者はいないが",
  BE_MORE_PATIENT: "しかし、どうぞ、より多くの患者デザイナーが通常締め切り日に申請するようにしてください",
  VIEW_PARTICIPANTS: "参加者を見る",
  VIEW_MY_POST: "投稿を見る",
  VIEW_PASS: "1回目のパスを表示",
  FINAL_WINNERS: "最終的な勝者",
  INVITATION_FROM_CLIENT: "クライアントからの招待状があります",
  VIEW_PROJECT_DETAIL: "プロジェクトの詳細を表示",
  VIEW_PROPOSAL_DETAIL: "提案の詳細を表示",
  ACCEPT_INTERVIEW: "面接を受け入れる",
  DECLINE_INTERVIEW: "面接を辞退する",
  REFER_A_FREELANCER: "フリーランサーを紹介する",
  BEST_REGARDS: "よろしくお願いします",
 POST_FULL_JOB_TEXT:"フルタイムのポジションで新しい仕事を投稿する",
 CONTINUE:"継続する",
 LINKEDIN_PROFILE_URL:"LinkedinプロファイルURL",
};
