let stockMarkets = [
    {   
        stock:"New York Stock Exchange",
        name: "United States",
        dial_code: "+1",
        code: "US",
      },
      {   
        stock:"NASDAQ Stock Exchange",
        name: "United States",
        dial_code: "+1",
        code: "US",
      },  
      {   
        stock:"Investors  Exchange",
        name: "United States",
        dial_code: "+1",
        code: "US",
      },  
      {   
        stock:"OTC Markets U.S",
        name: "United States",
        dial_code: "+1",
        code: "US",
      },  
      {
        stock:"Shanghai Stock Exchange",
        name: "China",
        dial_code: "+86",
        code: "CN",
      },
      {
        stock:"Shenzhen Stock Exchange",
        name: "China",
        dial_code: "+86",
        code: "CN",
      },
      {
        stock:"Tokyo Stock Exchange",
        name: "Japan",
        dial_code: "+81",
        code: "JP",
      },
      {
        stock:"Sapporo Security Exchange",
        name: "Japan",
        dial_code: "+81",
        code: "JP",
      },
      {
        stock:"Hong Kong Stock Exchange",
        name: "Hong Kong",
        dial_code: "+852",
        code: "HK",
      },
      {
        stock:"London Stock Exchange",
        name: "United Kingdom",
        dial_code: "+44",
        code: "GB",
      },
      {
        stock:"AIM Stock Exchange",
        name: "United Kingdom",
        dial_code: "+44",
        code: "GB",
      },
      {
        stock:"NEX Exchange",
        name: "United Kingdom",
        dial_code: "+44",
        code: "GB",
      },
      {
        stock:"Toronto Stock Exchange",
        name: "Canada",
        dial_code: "+1",
        code: "CA",
      },
      {
        stock:"Bourse de Montreal Options",
        name: "Canada",
        dial_code: "+1",
        code: "CA",
      },
      {
        stock:"Canadian National Stock Exchange",
        name: "Canada",
        dial_code: "+1",
        code: "CA",
      },
      {
        stock:"NEO Exchange",
        name: "Canada",
        dial_code: "+1",
        code: "CA",
      },
      {
        stock:"TSX Venture Exchange",
        name: "Canada",
        dial_code: "+1",
        code: "CA",
      },
      {
        stock:"India National Stock Exchange",
        name: "India",
        dial_code: "+91",
        code: "IN",
      },
      {
        stock:"Bombay Stock Exchange",
        name: "India",
        dial_code: "+91",
        code: "IN",
      },
      {
        stock:"Frankfurt Stock Exchange",
        name: "Germany",
        dial_code: "+49",
        code: "DE",
      },
      {
        stock:"Eurex Germany",
        name: "Germany",
        dial_code: "+49",
        code: "DE",
      },
      {
        stock:"Munich Stock Exchange",
        name: "Germany",
        dial_code: "+49",
        code: "DE",
      },
      {
        stock:"Stuttgart Stock Exchange",
        name: "Germany",
        dial_code: "+49",
        code: "DE",
      },
      {
        stock:"Borse Berlin Stock Exchange",
        name: "Germany",
        dial_code: "+49",
        code: "DE",
      },
      {
        stock:"Dusseldorf Berlin Stock Exchange",
        name: "Germany",
        dial_code: "+49",
        code: "DE",
      },
      {
        stock:"Deutsche Borse Xetra",
        name: "Germany",
        dial_code: "+49",
        code: "DE",
      },
      {
        stock:"Humburg Stock Exchange",
        name: "Germany",
        dial_code: "+49",
        code: "DE",
      },
      {
        stock:"Hannover Stock Exchange",
        name: "Germany",
        dial_code: "+49",
        code: "DE",
      },
      {
        stock:"Saudi Stock Exchange",
        name: "Saudi Arabia",
        dial_code: "+966",
        code: "SA",
      },
      {
        stock:"Copenhagen Stock Exchange",
        name: "Denmark",
        dial_code: "+45",
        code: "DK",
      },
      {
        stock:"South Korea Stock Exchange",
        name: "South Korea",
        dial_code: "+82",
        code: "KR",
      },
      {
        stock:"Korea Exchange(KOSDAQ)",
        name: "South Korea",
        dial_code: "+82",
        code: "KR",
      },
      {
        stock:"Swiss Stock Exchange",
        name: "Switzerland",
        dial_code: "+41",
        code: "CH",
      },
      {
        stock:"Euronext Paris Exchange",
        name: "France",
        dial_code: "+33",
        code: "FR",
      },
      {
        stock:"Taiwan Stock Exchange",
        name: "Taiwan, Province of China",
        dial_code: "+886",
        code: "TW",
      },
      {
        stock:"Taipel Exchange (TW)",
        name: "Taiwan, Province of China",
        dial_code: "+886",
        code: "TW",
      },
      {
        stock:"Australia Stock Exchange",
        name: "Australia",
        dial_code: "+61",
        code: "AU",
      },
      {
        stock:"Sydney Stock Exchange",
        name: "Australia",
        dial_code: "+61",
        code: "AU",
      },
      {
        stock:"National Stock Exchange of Australia ",
        name: "Australia",
        dial_code: "+61",
        code: "AU",
      },
      {
        stock:"Tehran Stock Exchange",
        name: "Iran, Islamic Republic of",
        dial_code: "+98",
        code: "IR",
      },
      {
        stock:"Iran Fara Bourse",
        name: "Iran, Islamic Republic of",
        dial_code: "+98",
        code: "IR",
      },
      {
        stock:"Johannesburg Stock Exchange",
        name: "South Africa",
        dial_code: "+27",
        code: "ZA",
      },
      {
        stock:"Brazil Stock Exchange",
        name: "Brazil",
        dial_code: "+55",
        code: "BR",
      },
      {
        stock:"Moscow Exchange",
        name: "Russia",
        dial_code: "+7",
        code: "RU",
      },
      {
        stock:"Madrid Stock Exchange",
        name: "Spain",
        dial_code: "+34",
        code: "ES",
      },
      {
        stock:"Euronext Amsterdam Stock Exchange",
        name: "Netherlands",
        dial_code: "+31",
        code: "NL",
      },
      {
        stock:"Singapore Exchange",
        name: "Singapore",
        dial_code: "+65",
        code: "SG",
      },
      {
        stock:"Italian Stock Exchange",
        name: "Italy",
        dial_code: "+39",
        code: "IT",
      },
      {
        stock:"Indonesia Stock Exchange",
        name: "Indonesia",
        dial_code: "+62",
        code: "ID",
      },
      {
        stock:"Mexican Stock Exchange",
        name: "Mexico",
        dial_code: "+52",
        code: "MX",
      },
      {
        stock:"Euronext Brussels",
        name: "Belgium",
        dial_code: "+32",
        code: "BE",
      },
      {
        stock:"Malaysia Stock Exchange",
        name: "Malaysia",
        dial_code: "+60",
        code: "MY",
      },
      {
        stock:"Abu Dhabi Securities Exchange",
        name: "United Arab Emirates",
        dial_code: "+971",
        code: "AE",
      },
      {
        stock:"Dubai Financial Market",
        name: "United Arab Emirates",
        dial_code: "+971",
        code: "AE",
      },
      {
        stock:"NASDAQ Dubai",
        name: "United Arab Emirates",
        dial_code: "+971",
        code: "AE",
      },
      {
        stock:"Tel Aviv Stock Exchange",
        name: "Israel",
        dial_code: "+972",
        code: "IL",
      },
      {
        stock:"Oslo Stock Exchange",
        name: "Norway",
        dial_code: "+47",
        code: "NO",
      },
      {
        stock:"Philippine Stock Exchange",
        name: "Philippines",
        dial_code: "+63",
        code: "PH",
      },
      {
        stock:"Ho Chi Minh Stock Exchange",
        name: "Viet Nam",
        dial_code: "+84",
        code: "VN",
      },
      {
        stock:"Warsaw Stock Exchange ",
        name: "Poland",
        dial_code: "+48",
        code: "PL",
      },
      {
        stock:"Santiago Stock Exchange ",
        name: "Chile",
        dial_code: "+56",
        code: "CL",
      },
      {
        stock:"Qatar Stock Exchange",
        name: "Qatar",
        dial_code: "+974",
        code: "QA",
      },
      {
        stock:"Istanbul Stock Exchange",
        name: "Turkey",
        dial_code: "+90",
        code: "TR",
      },
      {
        stock:"Vienna Stock Exchange",
        name: "Austria",
        dial_code: "+43",
        code: "AT",
      },
      {
        stock:"New Zealand Stock Exchange",
        name: "New Zealand",
        dial_code: "+64",
        code: "NZ",
      },
      {
        stock:"Colombia Stock Exchange",
        name: "Colombia",
        dial_code: "+57",
        code: "CO",
      },
      {
        stock:"Casabalnca Stock Exchange",
        name: "Morocco",
        dial_code: "+212",
        code: "MA",
      },
      {
        stock:"Luxembourg Stock Exchange",
        name: "Luxembourg",
        dial_code: "+352",
        code: "LU",
      },
      {
        stock:"Lima Stock Exchange",
        name: "Peru",
        dial_code: "+51",
        code: "PE",
      },
      {
        stock:"Kazakhstan Stock Exchange",
        name: "Kazakhstan",
        dial_code: "+7 7",
        code: "KZ",
      },
      {
        stock:"Euronext Lisbon" ,
        name: "Portugal",
        dial_code: "+351",
        code: "PT",
      },
      {
        stock:"Athens Stock Exchange" ,
        name: "Greece",
        dial_code: "+30",
        code: "GR",
      },
      {
        stock:"Chittagong Stock Exchange" ,
        name: "Bangladesh",
        dial_code: "+880",
        code: "BD",
      },
      {
        stock:"Dhaka Stock Exchange" ,
        name: "Bangladesh",
        dial_code: "+880",
        code: "BD",
      },
      {
        stock:"Egyptian Stock Exchange" ,
        name: "Egypt",
        dial_code: "+20",
        code: "EG",
      },
      {
        stock:"Nile Stock Exchange" ,
        name: "Egypt",
        dial_code: "+20",
        code: "EG",
      },
      {
        stock:"Budapest Stock Exchange" ,
        name: "Hungary",
        dial_code: "+36",
        code: "HU",
      },
      {
        stock:"Prague Stock Exchange" ,
        name: "Czech Republic",
        dial_code: "+420",
        code: "CZ",
      },
      {
        stock:"Bucharest Stock Exchange" ,
        name: "Romania",
        dial_code: "+40",
        code: "RO",
      },
      {
        stock:"Nairobi Securities Exchange" ,
        name: "Kenya",
        dial_code: "+254",
        code: "KE",
      },
      {
        stock:"Muscat Securities Exchange" ,
        name: "Oman",
        dial_code: "+968",
        code: "OM",
      },
      {
        stock:"Hanoi Stock Exchange" ,
        name: "Viet Nam",
        dial_code: "+84",
        code: "VN",
      },
      {
        stock:"Colombo Stock Exchange" ,
        name: "Sri Lanka",
        dial_code: "+94",
        code: "LK",
      },
      {
        stock:"Bulgarian Stock Exchange" ,
        name: "Bulgaria",
        dial_code: "+359",
        code: "BG",
      },
      {
        stock:"Jamaica Stock Exchange" ,
        name: "Jamaica",
        dial_code: "+1 876",
        code: "JM",
      },
      {
        stock:"Ljubljana Stock Exchange" ,
        name: "Slovenia",
        dial_code: "+386",
        code: "SI",
      },
      {
        stock:"Ghana Stock Exchange" ,
        name: "Ghana",
        dial_code: "+233",
        code: "GH",
      },
      {
        stock:"Beirut Stock Exchange" ,
        name: "Lebanon",
        dial_code: "+961",
        code: "LB",
      },
      {
        stock:"Stock Exchange of Mauritius" ,
        name: "Mauritius",
        dial_code: "+230",
        code: "MU",
      },
      {
        stock:"Bratislava Stock Exchange" ,
        name: "Slovakia",
        dial_code: "+421",
        code: "SK",
      },
      {
        stock:"Malta Stock Exchange" ,
        name: "Malta",
        dial_code: "+356",
        code: "MT",
      },
      {
        stock:"Palestinian Securities  Exchange" ,
        name: "Palestinian Territory, Occupied",
        dial_code: "+970",
        code: "PS",
      },
      {
        stock:"Ukraine  Exchange" ,
        name: "Ukraine",
        dial_code: "+380",
        code: "UA",
      },
      {
        stock:"PFTS Stock Exchange" ,
        name: "Ukraine",
        dial_code: "+380",
        code: "UA",
      },
      {
        stock:"Botswana  Stock Exchange" ,
        name: "Botswana",
        dial_code: "+267",
        code: "BW",
      },
      {
        stock:"Barbados  Stock Exchange" ,
        name: "Barbados",
        dial_code: "+1 246",
        code: "BB",
      },
      {
        stock:"Costa Rican  Stock Exchange" ,
        name: "Costa Rica",
        dial_code: "+506",
        code: "CR",
      },
      {
        stock:"Namibian  Stock Exchange" ,
        name: "Namibia",
        dial_code: "+264",
        code: "NA",
      },
      {
        stock:"Cayman Islands  Stock Exchange" ,
        name: "Cayman Islands",
        dial_code: "+ 345",
        code: "KY",
      },
      {
        stock:"Bermuda Stock Exchange" ,
        name: "Bermuda",
        dial_code: "+1 441",
        code: "BM",
      },
      {
        stock:"Argentinian Stock Exchange" ,
        name: "Argentina",
        dial_code: "+54",
        code: "AR",
      },
      {
        stock:"Banja Luka Stock Exchange" ,
        name: "Bosnia and Herzegovina",
        dial_code: "+387",
        code: "BA",
      },
      {
        stock:"Sarajevo Stock Exchange" ,
        name: "Bosnia and Herzegovina",
        dial_code: "+387",
        code: "BA",
      },
      {
        stock:"Bahrain Stock Exchange" ,
        name: "Bahrain",
        dial_code: "+973",
        code: "BH",
      },
      {
        stock:"Bolivian Stock Exchange" ,
        name: "Bolivia, Plurinational State of",
        dial_code: "+591",
        code: "BO",
      },
      {
        stock:"Belarusian Currency and  Stock Exchange" ,
        name: "Belarus",
        dial_code: "+375",
        code: "BY",
      },
      {
        stock:"BX Swiss",
        name: "Switzerland",
        dial_code: "+41",
        code: "CH",
      },
      {
        stock:"Regional Securities Exchange SA",
        name: "Cote d'Ivoire",
        dial_code: "+225",
        code: "CI",
      },
      {
        stock:"Guayaquil Stock Exchange" ,
        name: "Ecuador",
        dial_code: "+593",
        code: "EC",
      },
      {
        stock:"Tallinn Stock Exchange" ,
        name: "Estonia",
        dial_code: "+372",
        code: "EE",
      },
      {
        stock:"Helsinki Stock Exchange" ,
        name: "Finland",
        dial_code: "+358",
        code: "FI",
      },
      {
        stock:"The International Stock Exchange" ,
        name: "Guernsey",
        dial_code: "+44",
        code: "GG",
      },
      {
        stock:"Zagreb Stock Exchange" ,
        name: "Croatia",
        dial_code: "+385",
        code: "HR",
      },
      {
        stock:"Irish Stock Exchange" ,
        name: "Ireland",
        dial_code: "+353",
        code: "IE",
      },
      {
        stock:"Iceland Stock Exchange" ,
        name: "Iceland",
        dial_code: "+354",
        code: "IS",
      },
      {
        stock:"Amman Stock Exchange" ,
        name: "Jordan",
        dial_code: "+962",
        code: "JO",
      },
      {
        stock:"Kuwait Stock Exchange" ,
        name: "Kuwait",
        dial_code: "+965",
        code: "KW",
      },
      {
        stock:"Nasdaq Vilnius Stock Exchange" ,
        name: "Lithuania",
        dial_code: "+370",
        code: "LT",
      },
      {
        stock:"Riga Stock Exchange" ,
        name: "Latvia",
        dial_code: "+371",
        code: "LV",
      },
      {
        stock:"Montenegro Stock Exchange" ,
        name: "Montenegro",
        dial_code: "+382",
        code: "ME",
      },
      {
        stock:"Mongolian Stock Exchange" ,
        name: "Mongolia",
        dial_code: "+976",
        code: "MN",
      },
      {
        stock:"Nigerian Stock Exchange" ,
        name: "Nigeria",
        dial_code: "+234",
        code: "NG",
      },
      {
        stock:"Panama Stock Exchange" ,
        name: "Panama",
        dial_code: "+507",
        code: "PA",
      },
      {
        stock:"Pakistan Stock Exchange" ,
        name: "Pakistan",
        dial_code: "+92",
        code: "PK",
      },
      {
        stock:"Belgrade Stock Exchange" ,
        name: "Serbia",
        dial_code: "+381",
        code: "RS",
      },
      {
        stock:"Rwanda Stock Exchange" ,
        name: "Rwanda",
        dial_code: "+250",
        code: "RW",
      },
      {
        stock:"Stockholm Stock Exchange" ,
        name: "Sweden",
        dial_code: "+46",
        code: "SE",
      },
      {
        stock:"Nordic Growth Market" ,
        name: "Sweden",
        dial_code: "+46",
        code: "SE",
      },
      {
        stock:"Spotlight Stock Market" ,
        name: "Sweden",
        dial_code: "+46",
        code: "SE",
      },
      {
        stock:"Stock Exchange of Thailand" ,
        name: "Thailand",
        dial_code: "+66",
        code: "TH",
      },
      {
        stock:"Thailand Futures Exchange" ,
        name: "Thailand",
        dial_code: "+66",
        code: "TH",
      },
      {
        stock:"Dar es Salaam Stock Exchange" ,
        name: "Tanzania, United Republic of",
        dial_code: "+255",
        code: "TZ",
      },
      {
        stock:"Caracas Stock Exchange" ,
        name: "Venezuela, Bolivarian Republic of",
        dial_code: "+58",
        code: "VE",
      },
      {
        stock:"Zimbabwe Stock Exchange" ,
        name: "Zimbabwe",
        dial_code: "+263",
        code: "ZW",
      },
]

export const stockMarketsList = stockMarkets;