
export const LANGUAGE_CONST = "LANGUAGE_CONST";
export const PROJECT_TYPE_DROPDOWN = "PROJECT_TYPE_DROPDOWN";
export const ROUTE_CONST = "ROUTE_CONST";
export const PROJECT_SELECT_CONST = "PROJECT_SELECT_CONST";
export const PROJECT_CONFIRMATION_DATA_CONST = "PROJECT_CONFIRMATION_DATA_CONST";
export const SAVE_PROJECT_DATA_CONST = "SAVE_PROJECT_DATA_CONST";
export const REACT_ALERT = "communitytyContent/REACT_ALERT";
export const SET_CROSS_DOMAIN_DATA = "communitytyContent/SET_CROSS_DOMAIN_DATA";
export const SET_REGISTERED_USER_TYPES="SET_REGISTERED_USER_TYPES";
export const SET_ACTIVE_USER_TYPE="SET_ACTIVE_USER_TYPE";
export const UPDATE_REGISTER_USER_FLAG="UPDATE_REGISTER_USER_FLAG"
export const MY_CHANNEL_LIST = "communitytyContent/MY_CHANNEL_LIST";
export const SELECTED_CHANNEL = "communitytyContent/SELECTED_CHANNEL";
export const SETTINGS_CONST = "communitytyContent/SETTINGS_CONST";
export const TOGGLE_FOOTER_SETTINGS = "TOGGLE_FOOTER_SETTINGS";
export const GUEST_USER = "GUEST_USER";
export const REMOVE_CROSS_DOMAIN_DATA = "communitytyContent/REMOVE_CROSS_DOMAIN_DATA";
export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_USER_SUCCESSFULL = "GET_USER_SUCCESSFULL";
export const REMOVE_USER = "REMOVE_USER";
export const GET_BUSINESS_TYPES = "GET_BUSINESS_TYPES";
export const GET_PROFESSIONAL_FIELDS = "GET_PROFESSIONAL_FIELDS";
export const GET_COMPANY_TYPES = "GET_COMPANY_TYPES";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_STATES = "GET_STATES";
export const GET_CITIES = "GET_CITIES";
export const GET_USER_PROFILE_IMAGE = "GET_USER_PROFILE_IMAGE";
export const GET_REGISTRATION_PROOF = "GET_REGISTRATION_PROOF";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_FILES = "UPLOAD_FILES";
export const UPDATE_USER_PROFILE_IMAGE = "UPDATE_USER_PROFILE_IMAGE";
export const SET_ORG_PROFILE_IMAGE = "SET_ORG_PROFILE_IMAGE";
export const SET_ORG_OTHER_IMAGES = "SET_ORG_OTHER_IMAGES";
export const REMOVE_ORG_OTHER_IMAGE = "REMOVE_ORG_OTHER_IMAGE";
export const REMOVE_ORG_PROFILE_IMAGE = "REMOVE_ORG_PROFILE_IMAGE";
export const GET_ORGANIZATION = "GET_ORGANIZATION";
//constant image
export const GET_IMAGE_PREFIX= "dhihitu47nqhv.cloudfront.net/icons"//"d2res25sxj2mwn.cloudfront.net/icons";
export const GET_IMAGE_PREFIX1= "dhihitu47nqhv.cloudfront.net"


// constants for admin general settings : Chintan - 11 may 2021

export const GET_GENERAL_SETTING_REQUEST = "GET_GENERAL_SETTING_REQUEST"
export const GET_GENERAL_SETTING_REQUEST_SUCCESS = "GET_GENERAL_SETTING_REQUEST_SUCCESS"
export const GET_GENERAL_SETTING_REQUEST_FAILED = "GET_GENERAL_SETTING_REQUEST_FAILED"
export const GET_GENERAL_SETTING_REQUEST_CLEANUP = "GET_GENERAL_SETTING_REQUEST_CLEANUP"

export const ADD_GENERAL_SETTING_REQUEST = "ADD_GENERAL_SETTING_REQUEST"
export const ADD_GENERAL_SETTING_REQUEST_SUCCESS = "ADD_GENERAL_SETTING_REQUEST_SUCCESS"
export const ADD_GENERAL_SETTING_REQUEST_FAILED = "ADD_GENERAL_SETTING_REQUEST_FAILED"
export const ADD_GENERAL_SETTING_REQUEST_CLEANUP = "ADD_GENERAL_SETTING_REQUEST_CLEANUP"

export const UPDATE_GENERAL_SETTING_REQUEST = "UPDATE_GENERAL_SETTING_REQUEST"
export const UPDATE_GENERAL_SETTING_REQUEST_SUCCESS = "UPDATE_GENERAL_SETTING_REQUEST_SUCCESS"
export const UPDATE_GENERAL_SETTING_REQUEST_FAILED = "UPDATE_GENERAL_SETTING_REQUEST_FAILED"
export const UPDATE_GENERAL_SETTING_REQUEST_CLEANUP = "UPDATE_GENERAL_SETTING_REQUEST_CLEANUP"

export const DELETE_GENERAL_SETTING_REQUEST = "DELETE_GENERAL_SETTING_REQUEST"
export const DELETE_GENERAL_SETTING_REQUEST_SUCCESS = "DELETE_GENERAL_SETTING_REQUEST_SUCCESS"
export const DELETE_GENERAL_SETTING_REQUEST_FAILED = "DELETE_GENERAL_SETTING_REQUEST_FAILED"
export const DELETE_GENERAL_SETTING_REQUEST_CLEANUP = "DELETE_GENERAL_SETTING_REQUEST_CLEANUP"
export const GET_CONTESTS = "GET_CONTESTS";


// constants for getContest by project ID
export const GET_CONTEST_BY_PROJECT_ID_REQUEST = "GET_CONTEST_BY_PROJECT_ID_REQUEST"
export const GET_CONTEST_BY_PROJECT_ID_REQUEST_SUCCESS = "GET_CONTEST_BY_PROJECT_ID_REQUEST_SUCCESS"
export const GET_CONTEST_BY_PROJECT_ID_REQUEST_FAILED = "GET_CONTEST_BY_PROJECT_ID_REQUEST_FAILED"
export const GET_CONTEST_BY_PROJECT_ID_REQUEST_CLEANUP = "GET_CONTEST_BY_PROJECT_ID_REQUEST_CLEANUP"

// constants for IP and country data lookup
export const GET_IP_LOOKUP_DATA_REQUEST = "GET_IP_LOOKUP_DATA_REQUEST"
export const GET_IP_LOOKUP_DATA_REQUEST_SUCCESS = "GET_IP_LOOKUP_DATA_REQUEST_SUCCESS"
export const GET_IP_LOOKUP_DATA_REQUEST_FAILED = "GET_IP_LOOKUP_DATA_REQUEST_FAILED"
export const GET_IP_LOOKUP_DATA_REQUEST_CLEANUP = "GET_IP_LOOKUP_DATA_REQUEST_CLEANUP"

//Get Default Addess 


export const GET_DEFAULT_ADDRESS_DATA_REQUEST = "GET_DEFAULT_ADDRESS_DATA_REQUEST"
export const GET_DEFAULT_ADDRESS_DATA_REQUEST_SUCCESS = "GET_DEFAULT_ADDRESS_DATA_REQUEST_SUCCESS"
export const GET_DEFAULT_ADDRESS_DATA_REQUEST_FAILED = "GET_DEFAULT_ADDRESS_DATA_REQUEST_FAILED"
export const GET_DEFAULT_ADDRESS_DATA_REQUEST_CLEANUP = "GET_DEFAULT_ADDRESS_DATA_REQUEST_CLEANUP"


// freelancer auth

export const FREELANCER_CLIENT_AUTH_DATA="FREELANCER_CLIENT_AUTH_DATA"