export const dummyData = [
  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "Active",
    projectType: "Hourly",
    reviews: null,
    rating: null,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },
  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "Closed",
    projectType: "Hourly",
    reviews: "This Client is very good. loved working with him",
    rating: true,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "OnHold",
    projectType: "Hourly",
    reviews: "This Client is very good. loved working with him",
    rating: null,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "Active",
    projectType: "Milestone",
    action: {type : 'submit' , text : "Submit"},
    reviews: null,
    rating: null,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "Active",
    projectType: "Milestone",
    action: {type : 'request' , text : "Request Milestone"},
    reviews: null,
    rating: null,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "Closed",
    projectType: "Milestone",
    reviews: "This client is very rude",
    rating: true,
    action: null,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "WaitingForInitialDeposit",
    projectType: "Milestone",
    action: null,
    reviews: null,
    rating: null,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "Active",
    projectType: "FreeContract",
    reviews: null,
    rating: null,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "OnHold",
    projectType: "FreeContract",
    reviews: "This Client is very good. loved working with him",
    rating: null,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "Closed",
    projectType: "FreeContract",
    reviews: "This Client is very good. loved working with him",
    rating: true,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "Active",
    projectType: "Contest",
    reviews: "This client is super cool",
    rating: true,
    firstPass: true,
    award: "",
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "Closed",
    projectType: "Contest",
    reviews: null,
    rating: null,
    firstPass: false,
    award: "",
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },

  {
    abstractConcretePercentage: null,
    address: "Pakistan Telecommuication company limited",
    amountPerHour: null,
    blindPrice: "US$9.00",
    businessCategory: null,
    city: "Lahore",
    completionDateTime: "2021-10-22T07:32:11.705Z",
    contestComment: null,
    contestDescriptionDocAttach: null,
    country: "Pakistan",
    currencyCode: "USD",
    expectedCompletionDays: null,
    featuredContestPrice: null,
    freelancerLocation: null,
    freelancerType: "Any",
    fromSalary: null,
    isBlind: false,
    isFeaturedContest: false,
    isGuaranteed: false,
    isHireMoreFreelancer: false,
    isListed: false,
    isManualTimeAllow: false,
    isNeededNDA: true,
    isNeededSearchAssistant: true,
    isNeededUrgent: true,
    isPrivateNDAContest: false,
    isPromoted: false,
    isUntilHire: true,
    isUsingProjectTool: false,
    jobDescription:
      "ReactJS developers are front-end developers who build modern-day UI components to improvise application performance. They leverage their knowledge about JavaScript, HTML, CSS and work closely with testers, designers, web designers, and project managers to create a robust and effective application.30-Apr-2021",
    jobDescriptionDocAttached: null,
    jobSuccessScore: null,
    jobTitle: "ReactJs Developer",
    language: null,
    languageLevel: null,
    lastCompletedStep: null,
    latitude: null,
    logoDesignStyles: null,
    longitude: null,
    luxuryPublicPercentage: null,
    maleFemalePercentage: null,
    maxDailyRate: "160",
    maxHourlyRate: "16",
    maximumWeekHours: "30",
    milestones: [],
    minDailyRate: "90",
    minHourlyRate: "12",
    modernClassicPercentage: null,
    noOfDayAttendance: "4",
    noOfRequiredFreelancer: "4",
    noOfStar: null,
    offeredMilestones: null,
    packageDesignStyles: null,
    positionAvailableDate: "2021-11-21T07:34:08.250Z",
    postDateTime: "22-Oct-2021",
    postUserId: "NXEC8TDNE1QHDZP",
    privateContestNDADocumentPath: null,
    probationPeriod: null,
    projectBadge: "Contract",
    projectBudgetForMilestone: null,
    projectId: "20211022073211",
    projectLifeCycle: null,
    projectRemainingDays: null,
    projectScope: { projectScope: "web", projectSubscope: "website" },
    projectStatus: "Closed",
    projectType: "Contest",
    reviews: null,
    rating: null,
    firstPass: false,
    award: null,
    promotedToMoreFreelancerPrice: "US$9.00",
    proposalCount: null,
    regionId: "Punjab",
    salaryType: null,
    screeningQuestions:
      '[{"id":"5bc345d6-38d8-4eb1-a93b-9ee8d2ad94a8","question":"this is Question for testing"},{"id":"1b7ec748-eb1f-4693-998e-693e3d683d3e","question":"what is your age?"}]',
    secondPlacePrize: null,
    simpleComplexPercentage: null,
    skills: "Typescript,Javascript,Node,ReactJs,CSS",
    submissionExpirationDate: "2021-10-22T07:32:11.705Z",
    thirdPlacePrize: null,
    toSalary: null,
    winningAmount: null,
    yearsOfExperience: null,
    youngMutualPercentage: null,
  },
];
